/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BodyParamsEnrollmentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyParamsEnrollmentsInner{}

// BodyParamsEnrollmentsInner struct for BodyParamsEnrollmentsInner
type BodyParamsEnrollmentsInner struct {
	// A UID for an Enrollment object   (Java name `org.hisp.dhis.program.Enrollment`)
	Id string `json:"id"`
}

type _BodyParamsEnrollmentsInner BodyParamsEnrollmentsInner

// NewBodyParamsEnrollmentsInner instantiates a new BodyParamsEnrollmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyParamsEnrollmentsInner(id string) *BodyParamsEnrollmentsInner {
	this := BodyParamsEnrollmentsInner{}
	this.Id = id
	return &this
}

// NewBodyParamsEnrollmentsInnerWithDefaults instantiates a new BodyParamsEnrollmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyParamsEnrollmentsInnerWithDefaults() *BodyParamsEnrollmentsInner {
	this := BodyParamsEnrollmentsInner{}
	return &this
}

// GetId returns the Id field value
func (o *BodyParamsEnrollmentsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BodyParamsEnrollmentsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BodyParamsEnrollmentsInner) SetId(v string) {
	o.Id = v
}

func (o BodyParamsEnrollmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyParamsEnrollmentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *BodyParamsEnrollmentsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyParamsEnrollmentsInner := _BodyParamsEnrollmentsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBodyParamsEnrollmentsInner)

	if err != nil {
		return err
	}

	*o = BodyParamsEnrollmentsInner(varBodyParamsEnrollmentsInner)

	return err
}

type NullableBodyParamsEnrollmentsInner struct {
	value *BodyParamsEnrollmentsInner
	isSet bool
}

func (v NullableBodyParamsEnrollmentsInner) Get() *BodyParamsEnrollmentsInner {
	return v.value
}

func (v *NullableBodyParamsEnrollmentsInner) Set(val *BodyParamsEnrollmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyParamsEnrollmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyParamsEnrollmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyParamsEnrollmentsInner(val *BodyParamsEnrollmentsInner) *NullableBodyParamsEnrollmentsInner {
	return &NullableBodyParamsEnrollmentsInner{value: val, isSet: true}
}

func (v NullableBodyParamsEnrollmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyParamsEnrollmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
