/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CategoryOptionComboParamsLegendSet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryOptionComboParamsLegendSet{}

// CategoryOptionComboParamsLegendSet struct for CategoryOptionComboParamsLegendSet
type CategoryOptionComboParamsLegendSet struct {
	// A UID for an LegendSet object   (Java name `org.hisp.dhis.legend.LegendSet`)
	Id string `json:"id"`
}

type _CategoryOptionComboParamsLegendSet CategoryOptionComboParamsLegendSet

// NewCategoryOptionComboParamsLegendSet instantiates a new CategoryOptionComboParamsLegendSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryOptionComboParamsLegendSet(id string) *CategoryOptionComboParamsLegendSet {
	this := CategoryOptionComboParamsLegendSet{}
	this.Id = id
	return &this
}

// NewCategoryOptionComboParamsLegendSetWithDefaults instantiates a new CategoryOptionComboParamsLegendSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryOptionComboParamsLegendSetWithDefaults() *CategoryOptionComboParamsLegendSet {
	this := CategoryOptionComboParamsLegendSet{}
	return &this
}

// GetId returns the Id field value
func (o *CategoryOptionComboParamsLegendSet) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CategoryOptionComboParamsLegendSet) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CategoryOptionComboParamsLegendSet) SetId(v string) {
	o.Id = v
}

func (o CategoryOptionComboParamsLegendSet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryOptionComboParamsLegendSet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CategoryOptionComboParamsLegendSet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategoryOptionComboParamsLegendSet := _CategoryOptionComboParamsLegendSet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCategoryOptionComboParamsLegendSet)

	if err != nil {
		return err
	}

	*o = CategoryOptionComboParamsLegendSet(varCategoryOptionComboParamsLegendSet)

	return err
}

type NullableCategoryOptionComboParamsLegendSet struct {
	value *CategoryOptionComboParamsLegendSet
	isSet bool
}

func (v NullableCategoryOptionComboParamsLegendSet) Get() *CategoryOptionComboParamsLegendSet {
	return v.value
}

func (v *NullableCategoryOptionComboParamsLegendSet) Set(val *CategoryOptionComboParamsLegendSet) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryOptionComboParamsLegendSet) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryOptionComboParamsLegendSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryOptionComboParamsLegendSet(val *CategoryOptionComboParamsLegendSet) *NullableCategoryOptionComboParamsLegendSet {
	return &NullableCategoryOptionComboParamsLegendSet{value: val, isSet: true}
}

func (v NullableCategoryOptionComboParamsLegendSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryOptionComboParamsLegendSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
