/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.40
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the CategoryOptionGetObjectList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryOptionGetObjectList200Response{}

// CategoryOptionGetObjectList200Response struct for CategoryOptionGetObjectList200Response
type CategoryOptionGetObjectList200Response struct {
	Pager           *Pager           `json:"pager,omitempty"`
	CategoryOptions []CategoryOption `json:"categoryOptions,omitempty"`
}

// NewCategoryOptionGetObjectList200Response instantiates a new CategoryOptionGetObjectList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryOptionGetObjectList200Response() *CategoryOptionGetObjectList200Response {
	this := CategoryOptionGetObjectList200Response{}
	return &this
}

// NewCategoryOptionGetObjectList200ResponseWithDefaults instantiates a new CategoryOptionGetObjectList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryOptionGetObjectList200ResponseWithDefaults() *CategoryOptionGetObjectList200Response {
	this := CategoryOptionGetObjectList200Response{}
	return &this
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *CategoryOptionGetObjectList200Response) GetPager() Pager {
	if o == nil || IsNil(o.Pager) {
		var ret Pager
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryOptionGetObjectList200Response) GetPagerOk() (*Pager, bool) {
	if o == nil || IsNil(o.Pager) {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *CategoryOptionGetObjectList200Response) HasPager() bool {
	if o != nil && !IsNil(o.Pager) {
		return true
	}

	return false
}

// SetPager gets a reference to the given Pager and assigns it to the Pager field.
func (o *CategoryOptionGetObjectList200Response) SetPager(v Pager) {
	o.Pager = &v
}

// GetCategoryOptions returns the CategoryOptions field value if set, zero value otherwise.
func (o *CategoryOptionGetObjectList200Response) GetCategoryOptions() []CategoryOption {
	if o == nil || IsNil(o.CategoryOptions) {
		var ret []CategoryOption
		return ret
	}
	return o.CategoryOptions
}

// GetCategoryOptionsOk returns a tuple with the CategoryOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryOptionGetObjectList200Response) GetCategoryOptionsOk() ([]CategoryOption, bool) {
	if o == nil || IsNil(o.CategoryOptions) {
		return nil, false
	}
	return o.CategoryOptions, true
}

// HasCategoryOptions returns a boolean if a field has been set.
func (o *CategoryOptionGetObjectList200Response) HasCategoryOptions() bool {
	if o != nil && !IsNil(o.CategoryOptions) {
		return true
	}

	return false
}

// SetCategoryOptions gets a reference to the given []CategoryOption and assigns it to the CategoryOptions field.
func (o *CategoryOptionGetObjectList200Response) SetCategoryOptions(v []CategoryOption) {
	o.CategoryOptions = v
}

func (o CategoryOptionGetObjectList200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryOptionGetObjectList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pager) {
		toSerialize["pager"] = o.Pager
	}
	if !IsNil(o.CategoryOptions) {
		toSerialize["categoryOptions"] = o.CategoryOptions
	}
	return toSerialize, nil
}

type NullableCategoryOptionGetObjectList200Response struct {
	value *CategoryOptionGetObjectList200Response
	isSet bool
}

func (v NullableCategoryOptionGetObjectList200Response) Get() *CategoryOptionGetObjectList200Response {
	return v.value
}

func (v *NullableCategoryOptionGetObjectList200Response) Set(val *CategoryOptionGetObjectList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryOptionGetObjectList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryOptionGetObjectList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryOptionGetObjectList200Response(val *CategoryOptionGetObjectList200Response) *NullableCategoryOptionGetObjectList200Response {
	return &NullableCategoryOptionGetObjectList200Response{value: val, isSet: true}
}

func (v NullableCategoryOptionGetObjectList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryOptionGetObjectList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
