/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response - struct for CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response
type CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response struct {
	CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf *CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	ArrayOfCategoryOption                                                 *[]CategoryOption
}

// CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfAsCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response is a convenience function that returns CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf wrapped in CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response
func CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfAsCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response(v *CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response {
	return CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response{
		CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf: v,
	}
}

// []CategoryOptionAsCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response is a convenience function that returns []CategoryOption wrapped in CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response
func ArrayOfCategoryOptionAsCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response(v *[]CategoryOption) CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response {
	return CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response{
		ArrayOfCategoryOption: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf)
	if err == nil {
		jsonCategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf, _ := json.Marshal(dst.CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf)
		if string(jsonCategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) == "{}" { // empty struct
			dst.CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf = nil
		} else {
			match++
		}
	} else {
		dst.CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf = nil
	}

	// try to unmarshal data into ArrayOfCategoryOption
	err = newStrictDecoder(data).Decode(&dst.ArrayOfCategoryOption)
	if err == nil {
		jsonArrayOfCategoryOption, _ := json.Marshal(dst.ArrayOfCategoryOption)
		if string(jsonArrayOfCategoryOption) == "{}" { // empty struct
			dst.ArrayOfCategoryOption = nil
		} else {
			match++
		}
	} else {
		dst.ArrayOfCategoryOption = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf = nil
		dst.ArrayOfCategoryOption = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) MarshalJSON() ([]byte, error) {
	if src.CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf != nil {
		return json.Marshal(&src.CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf)
	}

	if src.ArrayOfCategoryOption != nil {
		return json.Marshal(&src.ArrayOfCategoryOption)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf != nil {
		return obj.CategoryOptionGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	}

	if obj.ArrayOfCategoryOption != nil {
		return obj.ArrayOfCategoryOption
	}

	// all schemas are nil
	return nil
}

type NullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response struct {
	value *CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response
	isSet bool
}

func (v NullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) Get() *CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response {
	return v.value
}

func (v *NullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) Set(val *CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response(val *CategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) *NullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response {
	return &NullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response{value: val, isSet: true}
}

func (v NullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryOptionGetObjectListGistGetObjectListGistAsCsv200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
