/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.40
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConfigurationInfrastructuralIndicators type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationInfrastructuralIndicators{}

// ConfigurationInfrastructuralIndicators A UID reference to a IndicatorGroup   (Java name `org.hisp.dhis.indicator.IndicatorGroup`)
type ConfigurationInfrastructuralIndicators struct {
	Id string `json:"id"`
}

type _ConfigurationInfrastructuralIndicators ConfigurationInfrastructuralIndicators

// NewConfigurationInfrastructuralIndicators instantiates a new ConfigurationInfrastructuralIndicators object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationInfrastructuralIndicators(id string) *ConfigurationInfrastructuralIndicators {
	this := ConfigurationInfrastructuralIndicators{}
	this.Id = id
	return &this
}

// NewConfigurationInfrastructuralIndicatorsWithDefaults instantiates a new ConfigurationInfrastructuralIndicators object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationInfrastructuralIndicatorsWithDefaults() *ConfigurationInfrastructuralIndicators {
	this := ConfigurationInfrastructuralIndicators{}
	return &this
}

// GetId returns the Id field value
func (o *ConfigurationInfrastructuralIndicators) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ConfigurationInfrastructuralIndicators) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ConfigurationInfrastructuralIndicators) SetId(v string) {
	o.Id = v
}

func (o ConfigurationInfrastructuralIndicators) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationInfrastructuralIndicators) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ConfigurationInfrastructuralIndicators) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigurationInfrastructuralIndicators := _ConfigurationInfrastructuralIndicators{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigurationInfrastructuralIndicators)

	if err != nil {
		return err
	}

	*o = ConfigurationInfrastructuralIndicators(varConfigurationInfrastructuralIndicators)

	return err
}

type NullableConfigurationInfrastructuralIndicators struct {
	value *ConfigurationInfrastructuralIndicators
	isSet bool
}

func (v NullableConfigurationInfrastructuralIndicators) Get() *ConfigurationInfrastructuralIndicators {
	return v.value
}

func (v *NullableConfigurationInfrastructuralIndicators) Set(val *ConfigurationInfrastructuralIndicators) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationInfrastructuralIndicators) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationInfrastructuralIndicators) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationInfrastructuralIndicators(val *ConfigurationInfrastructuralIndicators) *NullableConfigurationInfrastructuralIndicators {
	return &NullableConfigurationInfrastructuralIndicators{value: val, isSet: true}
}

func (v NullableConfigurationInfrastructuralIndicators) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationInfrastructuralIndicators) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
