/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"encoding/json"
)

// checks if the ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{}

// ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf struct for ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
type ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf struct {
	Entries   []map[string]interface{} `json:"entries,omitempty"`
	Pager     *GistPager               `json:"pager,omitempty"`
	Constants []Constant               `json:"constants,omitempty"`
}

// NewConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf instantiates a new ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf() *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	this := ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{}
	return &this
}

// NewConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfWithDefaults instantiates a new ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfWithDefaults() *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	this := ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetEntries() []map[string]interface{} {
	if o == nil || IsNil(o.Entries) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetEntriesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []map[string]interface{} and assigns it to the Entries field.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) SetEntries(v []map[string]interface{}) {
	o.Entries = v
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetPager() GistPager {
	if o == nil || IsNil(o.Pager) {
		var ret GistPager
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetPagerOk() (*GistPager, bool) {
	if o == nil || IsNil(o.Pager) {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) HasPager() bool {
	if o != nil && !IsNil(o.Pager) {
		return true
	}

	return false
}

// SetPager gets a reference to the given GistPager and assigns it to the Pager field.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) SetPager(v GistPager) {
	o.Pager = &v
}

// GetConstants returns the Constants field value if set, zero value otherwise.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetConstants() []Constant {
	if o == nil || IsNil(o.Constants) {
		var ret []Constant
		return ret
	}
	return o.Constants
}

// GetConstantsOk returns a tuple with the Constants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetConstantsOk() ([]Constant, bool) {
	if o == nil || IsNil(o.Constants) {
		return nil, false
	}
	return o.Constants, true
}

// HasConstants returns a boolean if a field has been set.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) HasConstants() bool {
	if o != nil && !IsNil(o.Constants) {
		return true
	}

	return false
}

// SetConstants gets a reference to the given []Constant and assigns it to the Constants field.
func (o *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) SetConstants(v []Constant) {
	o.Constants = v
}

func (o ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Pager) {
		toSerialize["pager"] = o.Pager
	}
	if !IsNil(o.Constants) {
		toSerialize["constants"] = o.Constants
	}
	return toSerialize, nil
}

type NullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf struct {
	value *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	isSet bool
}

func (v NullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) Get() *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	return v.value
}

func (v *NullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) Set(val *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf(val *ConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) *NullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	return &NullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{value: val, isSet: true}
}

func (v NullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConstantGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
