/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DataApprovalWorkflowParamsDataSetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataApprovalWorkflowParamsDataSetsInner{}

// DataApprovalWorkflowParamsDataSetsInner struct for DataApprovalWorkflowParamsDataSetsInner
type DataApprovalWorkflowParamsDataSetsInner struct {
	// A UID for an DataSet object   (Java name `org.hisp.dhis.dataset.DataSet`)
	Id string `json:"id"`
}

type _DataApprovalWorkflowParamsDataSetsInner DataApprovalWorkflowParamsDataSetsInner

// NewDataApprovalWorkflowParamsDataSetsInner instantiates a new DataApprovalWorkflowParamsDataSetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataApprovalWorkflowParamsDataSetsInner(id string) *DataApprovalWorkflowParamsDataSetsInner {
	this := DataApprovalWorkflowParamsDataSetsInner{}
	this.Id = id
	return &this
}

// NewDataApprovalWorkflowParamsDataSetsInnerWithDefaults instantiates a new DataApprovalWorkflowParamsDataSetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataApprovalWorkflowParamsDataSetsInnerWithDefaults() *DataApprovalWorkflowParamsDataSetsInner {
	this := DataApprovalWorkflowParamsDataSetsInner{}
	return &this
}

// GetId returns the Id field value
func (o *DataApprovalWorkflowParamsDataSetsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataApprovalWorkflowParamsDataSetsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataApprovalWorkflowParamsDataSetsInner) SetId(v string) {
	o.Id = v
}

func (o DataApprovalWorkflowParamsDataSetsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataApprovalWorkflowParamsDataSetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DataApprovalWorkflowParamsDataSetsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataApprovalWorkflowParamsDataSetsInner := _DataApprovalWorkflowParamsDataSetsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataApprovalWorkflowParamsDataSetsInner)

	if err != nil {
		return err
	}

	*o = DataApprovalWorkflowParamsDataSetsInner(varDataApprovalWorkflowParamsDataSetsInner)

	return err
}

type NullableDataApprovalWorkflowParamsDataSetsInner struct {
	value *DataApprovalWorkflowParamsDataSetsInner
	isSet bool
}

func (v NullableDataApprovalWorkflowParamsDataSetsInner) Get() *DataApprovalWorkflowParamsDataSetsInner {
	return v.value
}

func (v *NullableDataApprovalWorkflowParamsDataSetsInner) Set(val *DataApprovalWorkflowParamsDataSetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDataApprovalWorkflowParamsDataSetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDataApprovalWorkflowParamsDataSetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataApprovalWorkflowParamsDataSetsInner(val *DataApprovalWorkflowParamsDataSetsInner) *NullableDataApprovalWorkflowParamsDataSetsInner {
	return &NullableDataApprovalWorkflowParamsDataSetsInner{value: val, isSet: true}
}

func (v NullableDataApprovalWorkflowParamsDataSetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataApprovalWorkflowParamsDataSetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
