/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.40
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DataApprovalWorkflowDataApprovalLevelsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataApprovalWorkflowDataApprovalLevelsInner{}

// DataApprovalWorkflowDataApprovalLevelsInner A UID reference to a DataApprovalLevel   (Java name `org.hisp.dhis.dataapproval.DataApprovalLevel`)
type DataApprovalWorkflowDataApprovalLevelsInner struct {
	Id string `json:"id"`
}

type _DataApprovalWorkflowDataApprovalLevelsInner DataApprovalWorkflowDataApprovalLevelsInner

// NewDataApprovalWorkflowDataApprovalLevelsInner instantiates a new DataApprovalWorkflowDataApprovalLevelsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataApprovalWorkflowDataApprovalLevelsInner(id string) *DataApprovalWorkflowDataApprovalLevelsInner {
	this := DataApprovalWorkflowDataApprovalLevelsInner{}
	this.Id = id
	return &this
}

// NewDataApprovalWorkflowDataApprovalLevelsInnerWithDefaults instantiates a new DataApprovalWorkflowDataApprovalLevelsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataApprovalWorkflowDataApprovalLevelsInnerWithDefaults() *DataApprovalWorkflowDataApprovalLevelsInner {
	this := DataApprovalWorkflowDataApprovalLevelsInner{}
	return &this
}

// GetId returns the Id field value
func (o *DataApprovalWorkflowDataApprovalLevelsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataApprovalWorkflowDataApprovalLevelsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataApprovalWorkflowDataApprovalLevelsInner) SetId(v string) {
	o.Id = v
}

func (o DataApprovalWorkflowDataApprovalLevelsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataApprovalWorkflowDataApprovalLevelsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DataApprovalWorkflowDataApprovalLevelsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataApprovalWorkflowDataApprovalLevelsInner := _DataApprovalWorkflowDataApprovalLevelsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataApprovalWorkflowDataApprovalLevelsInner)

	if err != nil {
		return err
	}

	*o = DataApprovalWorkflowDataApprovalLevelsInner(varDataApprovalWorkflowDataApprovalLevelsInner)

	return err
}

type NullableDataApprovalWorkflowDataApprovalLevelsInner struct {
	value *DataApprovalWorkflowDataApprovalLevelsInner
	isSet bool
}

func (v NullableDataApprovalWorkflowDataApprovalLevelsInner) Get() *DataApprovalWorkflowDataApprovalLevelsInner {
	return v.value
}

func (v *NullableDataApprovalWorkflowDataApprovalLevelsInner) Set(val *DataApprovalWorkflowDataApprovalLevelsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDataApprovalWorkflowDataApprovalLevelsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDataApprovalWorkflowDataApprovalLevelsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataApprovalWorkflowDataApprovalLevelsInner(val *DataApprovalWorkflowDataApprovalLevelsInner) *NullableDataApprovalWorkflowDataApprovalLevelsInner {
	return &NullableDataApprovalWorkflowDataApprovalLevelsInner{value: val, isSet: true}
}

func (v NullableDataApprovalWorkflowDataApprovalLevelsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataApprovalWorkflowDataApprovalLevelsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
