/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ExpressionDimensionItemParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpressionDimensionItemParams{}

// ExpressionDimensionItemParams struct for ExpressionDimensionItemParams
type ExpressionDimensionItemParams struct {
	AggregateExportAttributeOptionCombo *string                               `json:"aggregateExportAttributeOptionCombo,omitempty"`
	AggregateExportCategoryOptionCombo  *string                               `json:"aggregateExportCategoryOptionCombo,omitempty"`
	AggregationType                     AggregationType                       `json:"aggregationType"`
	AttributeValues                     []AttributeValueParams                `json:"attributeValues,omitempty"`
	Code                                *string                               `json:"code,omitempty"`
	Created                             *time.Time                            `json:"created,omitempty"`
	CreatedBy                           *AggregateDataExchangeParamsCreatedBy `json:"createdBy,omitempty"`
	Description                         *string                               `json:"description,omitempty"`
	DimensionItem                       *string                               `json:"dimensionItem,omitempty"`
	DisplayDescription                  *string                               `json:"displayDescription,omitempty"`
	DisplayFormName                     *string                               `json:"displayFormName,omitempty"`
	DisplayName                         *string                               `json:"displayName,omitempty"`
	DisplayShortName                    *string                               `json:"displayShortName,omitempty"`
	Expression                          *string                               `json:"expression,omitempty"`
	Favorite                            *bool                                 `json:"favorite,omitempty"`
	Favorites                           []string                              `json:"favorites,omitempty"`
	FormName                            *string                               `json:"formName,omitempty"`
	Id                                  *string                               `json:"id,omitempty"`
	LastUpdated                         *time.Time                            `json:"lastUpdated,omitempty"`
	LastUpdatedBy                       *AggregateDataExchangeParamsCreatedBy `json:"lastUpdatedBy,omitempty"`
	LegendSet                           *CategoryOptionComboParamsLegendSet   `json:"legendSet,omitempty"`
	LegendSets                          []CategoryOptionComboParamsLegendSet  `json:"legendSets,omitempty"`
	MissingValueStrategy                MissingValueStrategy                  `json:"missingValueStrategy"`
	Name                                *string                               `json:"name,omitempty"`
	QueryMods                           *QueryModifiers                       `json:"queryMods,omitempty"`
	Sharing                             *Sharing                              `json:"sharing,omitempty"`
	ShortName                           *string                               `json:"shortName,omitempty"`
	SlidingWindow                       *bool                                 `json:"slidingWindow,omitempty"`
	Translations                        []Translation                         `json:"translations,omitempty"`
}

type _ExpressionDimensionItemParams ExpressionDimensionItemParams

// NewExpressionDimensionItemParams instantiates a new ExpressionDimensionItemParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpressionDimensionItemParams(aggregationType AggregationType, missingValueStrategy MissingValueStrategy) *ExpressionDimensionItemParams {
	this := ExpressionDimensionItemParams{}
	this.AggregationType = aggregationType
	this.MissingValueStrategy = missingValueStrategy
	return &this
}

// NewExpressionDimensionItemParamsWithDefaults instantiates a new ExpressionDimensionItemParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpressionDimensionItemParamsWithDefaults() *ExpressionDimensionItemParams {
	this := ExpressionDimensionItemParams{}
	return &this
}

// GetAggregateExportAttributeOptionCombo returns the AggregateExportAttributeOptionCombo field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetAggregateExportAttributeOptionCombo() string {
	if o == nil || IsNil(o.AggregateExportAttributeOptionCombo) {
		var ret string
		return ret
	}
	return *o.AggregateExportAttributeOptionCombo
}

// GetAggregateExportAttributeOptionComboOk returns a tuple with the AggregateExportAttributeOptionCombo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetAggregateExportAttributeOptionComboOk() (*string, bool) {
	if o == nil || IsNil(o.AggregateExportAttributeOptionCombo) {
		return nil, false
	}
	return o.AggregateExportAttributeOptionCombo, true
}

// HasAggregateExportAttributeOptionCombo returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasAggregateExportAttributeOptionCombo() bool {
	if o != nil && !IsNil(o.AggregateExportAttributeOptionCombo) {
		return true
	}

	return false
}

// SetAggregateExportAttributeOptionCombo gets a reference to the given string and assigns it to the AggregateExportAttributeOptionCombo field.
func (o *ExpressionDimensionItemParams) SetAggregateExportAttributeOptionCombo(v string) {
	o.AggregateExportAttributeOptionCombo = &v
}

// GetAggregateExportCategoryOptionCombo returns the AggregateExportCategoryOptionCombo field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetAggregateExportCategoryOptionCombo() string {
	if o == nil || IsNil(o.AggregateExportCategoryOptionCombo) {
		var ret string
		return ret
	}
	return *o.AggregateExportCategoryOptionCombo
}

// GetAggregateExportCategoryOptionComboOk returns a tuple with the AggregateExportCategoryOptionCombo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetAggregateExportCategoryOptionComboOk() (*string, bool) {
	if o == nil || IsNil(o.AggregateExportCategoryOptionCombo) {
		return nil, false
	}
	return o.AggregateExportCategoryOptionCombo, true
}

// HasAggregateExportCategoryOptionCombo returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasAggregateExportCategoryOptionCombo() bool {
	if o != nil && !IsNil(o.AggregateExportCategoryOptionCombo) {
		return true
	}

	return false
}

// SetAggregateExportCategoryOptionCombo gets a reference to the given string and assigns it to the AggregateExportCategoryOptionCombo field.
func (o *ExpressionDimensionItemParams) SetAggregateExportCategoryOptionCombo(v string) {
	o.AggregateExportCategoryOptionCombo = &v
}

// GetAggregationType returns the AggregationType field value
func (o *ExpressionDimensionItemParams) GetAggregationType() AggregationType {
	if o == nil {
		var ret AggregationType
		return ret
	}

	return o.AggregationType
}

// GetAggregationTypeOk returns a tuple with the AggregationType field value
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetAggregationTypeOk() (*AggregationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AggregationType, true
}

// SetAggregationType sets field value
func (o *ExpressionDimensionItemParams) SetAggregationType(v AggregationType) {
	o.AggregationType = v
}

// GetAttributeValues returns the AttributeValues field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetAttributeValues() []AttributeValueParams {
	if o == nil || IsNil(o.AttributeValues) {
		var ret []AttributeValueParams
		return ret
	}
	return o.AttributeValues
}

// GetAttributeValuesOk returns a tuple with the AttributeValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetAttributeValuesOk() ([]AttributeValueParams, bool) {
	if o == nil || IsNil(o.AttributeValues) {
		return nil, false
	}
	return o.AttributeValues, true
}

// HasAttributeValues returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasAttributeValues() bool {
	if o != nil && !IsNil(o.AttributeValues) {
		return true
	}

	return false
}

// SetAttributeValues gets a reference to the given []AttributeValueParams and assigns it to the AttributeValues field.
func (o *ExpressionDimensionItemParams) SetAttributeValues(v []AttributeValueParams) {
	o.AttributeValues = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ExpressionDimensionItemParams) SetCode(v string) {
	o.Code = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ExpressionDimensionItemParams) SetCreated(v time.Time) {
	o.Created = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetCreatedBy() AggregateDataExchangeParamsCreatedBy {
	if o == nil || IsNil(o.CreatedBy) {
		var ret AggregateDataExchangeParamsCreatedBy
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetCreatedByOk() (*AggregateDataExchangeParamsCreatedBy, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given AggregateDataExchangeParamsCreatedBy and assigns it to the CreatedBy field.
func (o *ExpressionDimensionItemParams) SetCreatedBy(v AggregateDataExchangeParamsCreatedBy) {
	o.CreatedBy = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ExpressionDimensionItemParams) SetDescription(v string) {
	o.Description = &v
}

// GetDimensionItem returns the DimensionItem field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetDimensionItem() string {
	if o == nil || IsNil(o.DimensionItem) {
		var ret string
		return ret
	}
	return *o.DimensionItem
}

// GetDimensionItemOk returns a tuple with the DimensionItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetDimensionItemOk() (*string, bool) {
	if o == nil || IsNil(o.DimensionItem) {
		return nil, false
	}
	return o.DimensionItem, true
}

// HasDimensionItem returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasDimensionItem() bool {
	if o != nil && !IsNil(o.DimensionItem) {
		return true
	}

	return false
}

// SetDimensionItem gets a reference to the given string and assigns it to the DimensionItem field.
func (o *ExpressionDimensionItemParams) SetDimensionItem(v string) {
	o.DimensionItem = &v
}

// GetDisplayDescription returns the DisplayDescription field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetDisplayDescription() string {
	if o == nil || IsNil(o.DisplayDescription) {
		var ret string
		return ret
	}
	return *o.DisplayDescription
}

// GetDisplayDescriptionOk returns a tuple with the DisplayDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetDisplayDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayDescription) {
		return nil, false
	}
	return o.DisplayDescription, true
}

// HasDisplayDescription returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasDisplayDescription() bool {
	if o != nil && !IsNil(o.DisplayDescription) {
		return true
	}

	return false
}

// SetDisplayDescription gets a reference to the given string and assigns it to the DisplayDescription field.
func (o *ExpressionDimensionItemParams) SetDisplayDescription(v string) {
	o.DisplayDescription = &v
}

// GetDisplayFormName returns the DisplayFormName field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetDisplayFormName() string {
	if o == nil || IsNil(o.DisplayFormName) {
		var ret string
		return ret
	}
	return *o.DisplayFormName
}

// GetDisplayFormNameOk returns a tuple with the DisplayFormName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetDisplayFormNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayFormName) {
		return nil, false
	}
	return o.DisplayFormName, true
}

// HasDisplayFormName returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasDisplayFormName() bool {
	if o != nil && !IsNil(o.DisplayFormName) {
		return true
	}

	return false
}

// SetDisplayFormName gets a reference to the given string and assigns it to the DisplayFormName field.
func (o *ExpressionDimensionItemParams) SetDisplayFormName(v string) {
	o.DisplayFormName = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ExpressionDimensionItemParams) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDisplayShortName returns the DisplayShortName field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetDisplayShortName() string {
	if o == nil || IsNil(o.DisplayShortName) {
		var ret string
		return ret
	}
	return *o.DisplayShortName
}

// GetDisplayShortNameOk returns a tuple with the DisplayShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetDisplayShortNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayShortName) {
		return nil, false
	}
	return o.DisplayShortName, true
}

// HasDisplayShortName returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasDisplayShortName() bool {
	if o != nil && !IsNil(o.DisplayShortName) {
		return true
	}

	return false
}

// SetDisplayShortName gets a reference to the given string and assigns it to the DisplayShortName field.
func (o *ExpressionDimensionItemParams) SetDisplayShortName(v string) {
	o.DisplayShortName = &v
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetExpression() string {
	if o == nil || IsNil(o.Expression) {
		var ret string
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given string and assigns it to the Expression field.
func (o *ExpressionDimensionItemParams) SetExpression(v string) {
	o.Expression = &v
}

// GetFavorite returns the Favorite field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetFavorite() bool {
	if o == nil || IsNil(o.Favorite) {
		var ret bool
		return ret
	}
	return *o.Favorite
}

// GetFavoriteOk returns a tuple with the Favorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetFavoriteOk() (*bool, bool) {
	if o == nil || IsNil(o.Favorite) {
		return nil, false
	}
	return o.Favorite, true
}

// HasFavorite returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasFavorite() bool {
	if o != nil && !IsNil(o.Favorite) {
		return true
	}

	return false
}

// SetFavorite gets a reference to the given bool and assigns it to the Favorite field.
func (o *ExpressionDimensionItemParams) SetFavorite(v bool) {
	o.Favorite = &v
}

// GetFavorites returns the Favorites field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetFavorites() []string {
	if o == nil || IsNil(o.Favorites) {
		var ret []string
		return ret
	}
	return o.Favorites
}

// GetFavoritesOk returns a tuple with the Favorites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetFavoritesOk() ([]string, bool) {
	if o == nil || IsNil(o.Favorites) {
		return nil, false
	}
	return o.Favorites, true
}

// HasFavorites returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasFavorites() bool {
	if o != nil && !IsNil(o.Favorites) {
		return true
	}

	return false
}

// SetFavorites gets a reference to the given []string and assigns it to the Favorites field.
func (o *ExpressionDimensionItemParams) SetFavorites(v []string) {
	o.Favorites = v
}

// GetFormName returns the FormName field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetFormName() string {
	if o == nil || IsNil(o.FormName) {
		var ret string
		return ret
	}
	return *o.FormName
}

// GetFormNameOk returns a tuple with the FormName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetFormNameOk() (*string, bool) {
	if o == nil || IsNil(o.FormName) {
		return nil, false
	}
	return o.FormName, true
}

// HasFormName returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasFormName() bool {
	if o != nil && !IsNil(o.FormName) {
		return true
	}

	return false
}

// SetFormName gets a reference to the given string and assigns it to the FormName field.
func (o *ExpressionDimensionItemParams) SetFormName(v string) {
	o.FormName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExpressionDimensionItemParams) SetId(v string) {
	o.Id = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given time.Time and assigns it to the LastUpdated field.
func (o *ExpressionDimensionItemParams) SetLastUpdated(v time.Time) {
	o.LastUpdated = &v
}

// GetLastUpdatedBy returns the LastUpdatedBy field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetLastUpdatedBy() AggregateDataExchangeParamsCreatedBy {
	if o == nil || IsNil(o.LastUpdatedBy) {
		var ret AggregateDataExchangeParamsCreatedBy
		return ret
	}
	return *o.LastUpdatedBy
}

// GetLastUpdatedByOk returns a tuple with the LastUpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetLastUpdatedByOk() (*AggregateDataExchangeParamsCreatedBy, bool) {
	if o == nil || IsNil(o.LastUpdatedBy) {
		return nil, false
	}
	return o.LastUpdatedBy, true
}

// HasLastUpdatedBy returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasLastUpdatedBy() bool {
	if o != nil && !IsNil(o.LastUpdatedBy) {
		return true
	}

	return false
}

// SetLastUpdatedBy gets a reference to the given AggregateDataExchangeParamsCreatedBy and assigns it to the LastUpdatedBy field.
func (o *ExpressionDimensionItemParams) SetLastUpdatedBy(v AggregateDataExchangeParamsCreatedBy) {
	o.LastUpdatedBy = &v
}

// GetLegendSet returns the LegendSet field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetLegendSet() CategoryOptionComboParamsLegendSet {
	if o == nil || IsNil(o.LegendSet) {
		var ret CategoryOptionComboParamsLegendSet
		return ret
	}
	return *o.LegendSet
}

// GetLegendSetOk returns a tuple with the LegendSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetLegendSetOk() (*CategoryOptionComboParamsLegendSet, bool) {
	if o == nil || IsNil(o.LegendSet) {
		return nil, false
	}
	return o.LegendSet, true
}

// HasLegendSet returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasLegendSet() bool {
	if o != nil && !IsNil(o.LegendSet) {
		return true
	}

	return false
}

// SetLegendSet gets a reference to the given CategoryOptionComboParamsLegendSet and assigns it to the LegendSet field.
func (o *ExpressionDimensionItemParams) SetLegendSet(v CategoryOptionComboParamsLegendSet) {
	o.LegendSet = &v
}

// GetLegendSets returns the LegendSets field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetLegendSets() []CategoryOptionComboParamsLegendSet {
	if o == nil || IsNil(o.LegendSets) {
		var ret []CategoryOptionComboParamsLegendSet
		return ret
	}
	return o.LegendSets
}

// GetLegendSetsOk returns a tuple with the LegendSets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetLegendSetsOk() ([]CategoryOptionComboParamsLegendSet, bool) {
	if o == nil || IsNil(o.LegendSets) {
		return nil, false
	}
	return o.LegendSets, true
}

// HasLegendSets returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasLegendSets() bool {
	if o != nil && !IsNil(o.LegendSets) {
		return true
	}

	return false
}

// SetLegendSets gets a reference to the given []CategoryOptionComboParamsLegendSet and assigns it to the LegendSets field.
func (o *ExpressionDimensionItemParams) SetLegendSets(v []CategoryOptionComboParamsLegendSet) {
	o.LegendSets = v
}

// GetMissingValueStrategy returns the MissingValueStrategy field value
func (o *ExpressionDimensionItemParams) GetMissingValueStrategy() MissingValueStrategy {
	if o == nil {
		var ret MissingValueStrategy
		return ret
	}

	return o.MissingValueStrategy
}

// GetMissingValueStrategyOk returns a tuple with the MissingValueStrategy field value
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetMissingValueStrategyOk() (*MissingValueStrategy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MissingValueStrategy, true
}

// SetMissingValueStrategy sets field value
func (o *ExpressionDimensionItemParams) SetMissingValueStrategy(v MissingValueStrategy) {
	o.MissingValueStrategy = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ExpressionDimensionItemParams) SetName(v string) {
	o.Name = &v
}

// GetQueryMods returns the QueryMods field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetQueryMods() QueryModifiers {
	if o == nil || IsNil(o.QueryMods) {
		var ret QueryModifiers
		return ret
	}
	return *o.QueryMods
}

// GetQueryModsOk returns a tuple with the QueryMods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetQueryModsOk() (*QueryModifiers, bool) {
	if o == nil || IsNil(o.QueryMods) {
		return nil, false
	}
	return o.QueryMods, true
}

// HasQueryMods returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasQueryMods() bool {
	if o != nil && !IsNil(o.QueryMods) {
		return true
	}

	return false
}

// SetQueryMods gets a reference to the given QueryModifiers and assigns it to the QueryMods field.
func (o *ExpressionDimensionItemParams) SetQueryMods(v QueryModifiers) {
	o.QueryMods = &v
}

// GetSharing returns the Sharing field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetSharing() Sharing {
	if o == nil || IsNil(o.Sharing) {
		var ret Sharing
		return ret
	}
	return *o.Sharing
}

// GetSharingOk returns a tuple with the Sharing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetSharingOk() (*Sharing, bool) {
	if o == nil || IsNil(o.Sharing) {
		return nil, false
	}
	return o.Sharing, true
}

// HasSharing returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasSharing() bool {
	if o != nil && !IsNil(o.Sharing) {
		return true
	}

	return false
}

// SetSharing gets a reference to the given Sharing and assigns it to the Sharing field.
func (o *ExpressionDimensionItemParams) SetSharing(v Sharing) {
	o.Sharing = &v
}

// GetShortName returns the ShortName field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetShortName() string {
	if o == nil || IsNil(o.ShortName) {
		var ret string
		return ret
	}
	return *o.ShortName
}

// GetShortNameOk returns a tuple with the ShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetShortNameOk() (*string, bool) {
	if o == nil || IsNil(o.ShortName) {
		return nil, false
	}
	return o.ShortName, true
}

// HasShortName returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasShortName() bool {
	if o != nil && !IsNil(o.ShortName) {
		return true
	}

	return false
}

// SetShortName gets a reference to the given string and assigns it to the ShortName field.
func (o *ExpressionDimensionItemParams) SetShortName(v string) {
	o.ShortName = &v
}

// GetSlidingWindow returns the SlidingWindow field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetSlidingWindow() bool {
	if o == nil || IsNil(o.SlidingWindow) {
		var ret bool
		return ret
	}
	return *o.SlidingWindow
}

// GetSlidingWindowOk returns a tuple with the SlidingWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetSlidingWindowOk() (*bool, bool) {
	if o == nil || IsNil(o.SlidingWindow) {
		return nil, false
	}
	return o.SlidingWindow, true
}

// HasSlidingWindow returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasSlidingWindow() bool {
	if o != nil && !IsNil(o.SlidingWindow) {
		return true
	}

	return false
}

// SetSlidingWindow gets a reference to the given bool and assigns it to the SlidingWindow field.
func (o *ExpressionDimensionItemParams) SetSlidingWindow(v bool) {
	o.SlidingWindow = &v
}

// GetTranslations returns the Translations field value if set, zero value otherwise.
func (o *ExpressionDimensionItemParams) GetTranslations() []Translation {
	if o == nil || IsNil(o.Translations) {
		var ret []Translation
		return ret
	}
	return o.Translations
}

// GetTranslationsOk returns a tuple with the Translations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionDimensionItemParams) GetTranslationsOk() ([]Translation, bool) {
	if o == nil || IsNil(o.Translations) {
		return nil, false
	}
	return o.Translations, true
}

// HasTranslations returns a boolean if a field has been set.
func (o *ExpressionDimensionItemParams) HasTranslations() bool {
	if o != nil && !IsNil(o.Translations) {
		return true
	}

	return false
}

// SetTranslations gets a reference to the given []Translation and assigns it to the Translations field.
func (o *ExpressionDimensionItemParams) SetTranslations(v []Translation) {
	o.Translations = v
}

func (o ExpressionDimensionItemParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpressionDimensionItemParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AggregateExportAttributeOptionCombo) {
		toSerialize["aggregateExportAttributeOptionCombo"] = o.AggregateExportAttributeOptionCombo
	}
	if !IsNil(o.AggregateExportCategoryOptionCombo) {
		toSerialize["aggregateExportCategoryOptionCombo"] = o.AggregateExportCategoryOptionCombo
	}
	toSerialize["aggregationType"] = o.AggregationType
	if !IsNil(o.AttributeValues) {
		toSerialize["attributeValues"] = o.AttributeValues
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DimensionItem) {
		toSerialize["dimensionItem"] = o.DimensionItem
	}
	if !IsNil(o.DisplayDescription) {
		toSerialize["displayDescription"] = o.DisplayDescription
	}
	if !IsNil(o.DisplayFormName) {
		toSerialize["displayFormName"] = o.DisplayFormName
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.DisplayShortName) {
		toSerialize["displayShortName"] = o.DisplayShortName
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	if !IsNil(o.Favorite) {
		toSerialize["favorite"] = o.Favorite
	}
	if !IsNil(o.Favorites) {
		toSerialize["favorites"] = o.Favorites
	}
	if !IsNil(o.FormName) {
		toSerialize["formName"] = o.FormName
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.LastUpdatedBy) {
		toSerialize["lastUpdatedBy"] = o.LastUpdatedBy
	}
	if !IsNil(o.LegendSet) {
		toSerialize["legendSet"] = o.LegendSet
	}
	if !IsNil(o.LegendSets) {
		toSerialize["legendSets"] = o.LegendSets
	}
	toSerialize["missingValueStrategy"] = o.MissingValueStrategy
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.QueryMods) {
		toSerialize["queryMods"] = o.QueryMods
	}
	if !IsNil(o.Sharing) {
		toSerialize["sharing"] = o.Sharing
	}
	if !IsNil(o.ShortName) {
		toSerialize["shortName"] = o.ShortName
	}
	if !IsNil(o.SlidingWindow) {
		toSerialize["slidingWindow"] = o.SlidingWindow
	}
	if !IsNil(o.Translations) {
		toSerialize["translations"] = o.Translations
	}
	return toSerialize, nil
}

func (o *ExpressionDimensionItemParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"aggregationType",
		"missingValueStrategy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpressionDimensionItemParams := _ExpressionDimensionItemParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExpressionDimensionItemParams)

	if err != nil {
		return err
	}

	*o = ExpressionDimensionItemParams(varExpressionDimensionItemParams)

	return err
}

type NullableExpressionDimensionItemParams struct {
	value *ExpressionDimensionItemParams
	isSet bool
}

func (v NullableExpressionDimensionItemParams) Get() *ExpressionDimensionItemParams {
	return v.value
}

func (v *NullableExpressionDimensionItemParams) Set(val *ExpressionDimensionItemParams) {
	v.value = val
	v.isSet = true
}

func (v NullableExpressionDimensionItemParams) IsSet() bool {
	return v.isSet
}

func (v *NullableExpressionDimensionItemParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpressionDimensionItemParams(val *ExpressionDimensionItemParams) *NullableExpressionDimensionItemParams {
	return &NullableExpressionDimensionItemParams{value: val, isSet: true}
}

func (v NullableExpressionDimensionItemParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpressionDimensionItemParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
