/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{}

// IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf struct for IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
type IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf struct {
	Entries             []map[string]interface{} `json:"entries,omitempty"`
	Pager               *GistPager               `json:"pager,omitempty"`
	IdentifiableObjects []IdentifiableObject     `json:"identifiableObjects,omitempty"`
}

// NewIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf instantiates a new IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf() *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	this := IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{}
	return &this
}

// NewIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfWithDefaults instantiates a new IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfWithDefaults() *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	this := IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetEntries() []map[string]interface{} {
	if o == nil || IsNil(o.Entries) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetEntriesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []map[string]interface{} and assigns it to the Entries field.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) SetEntries(v []map[string]interface{}) {
	o.Entries = v
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetPager() GistPager {
	if o == nil || IsNil(o.Pager) {
		var ret GistPager
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetPagerOk() (*GistPager, bool) {
	if o == nil || IsNil(o.Pager) {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) HasPager() bool {
	if o != nil && !IsNil(o.Pager) {
		return true
	}

	return false
}

// SetPager gets a reference to the given GistPager and assigns it to the Pager field.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) SetPager(v GistPager) {
	o.Pager = &v
}

// GetIdentifiableObjects returns the IdentifiableObjects field value if set, zero value otherwise.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetIdentifiableObjects() []IdentifiableObject {
	if o == nil || IsNil(o.IdentifiableObjects) {
		var ret []IdentifiableObject
		return ret
	}
	return o.IdentifiableObjects
}

// GetIdentifiableObjectsOk returns a tuple with the IdentifiableObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetIdentifiableObjectsOk() ([]IdentifiableObject, bool) {
	if o == nil || IsNil(o.IdentifiableObjects) {
		return nil, false
	}
	return o.IdentifiableObjects, true
}

// HasIdentifiableObjects returns a boolean if a field has been set.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) HasIdentifiableObjects() bool {
	if o != nil && !IsNil(o.IdentifiableObjects) {
		return true
	}

	return false
}

// SetIdentifiableObjects gets a reference to the given []IdentifiableObject and assigns it to the IdentifiableObjects field.
func (o *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) SetIdentifiableObjects(v []IdentifiableObject) {
	o.IdentifiableObjects = v
}

func (o IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Pager) {
		toSerialize["pager"] = o.Pager
	}
	if !IsNil(o.IdentifiableObjects) {
		toSerialize["identifiableObjects"] = o.IdentifiableObjects
	}
	return toSerialize, nil
}

type NullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf struct {
	value *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	isSet bool
}

func (v NullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) Get() *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	return v.value
}

func (v *NullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) Set(val *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf(val *IdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) *NullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	return &NullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{value: val, isSet: true}
}

func (v NullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentifiableObjectGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
