/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{}

// OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf struct for OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
type OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf struct {
	Entries                     []map[string]interface{}          `json:"entries,omitempty"`
	Pager                       *GistPager                        `json:"pager,omitempty"`
	OAuth2AuthorizationConsents []Dhis2OAuth2AuthorizationConsent `json:"oAuth2AuthorizationConsents,omitempty"`
}

// NewOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf instantiates a new OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf() *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	this := OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{}
	return &this
}

// NewOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfWithDefaults instantiates a new OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfWithDefaults() *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	this := OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetEntries() []map[string]interface{} {
	if o == nil || IsNil(o.Entries) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetEntriesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []map[string]interface{} and assigns it to the Entries field.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) SetEntries(v []map[string]interface{}) {
	o.Entries = v
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetPager() GistPager {
	if o == nil || IsNil(o.Pager) {
		var ret GistPager
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetPagerOk() (*GistPager, bool) {
	if o == nil || IsNil(o.Pager) {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) HasPager() bool {
	if o != nil && !IsNil(o.Pager) {
		return true
	}

	return false
}

// SetPager gets a reference to the given GistPager and assigns it to the Pager field.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) SetPager(v GistPager) {
	o.Pager = &v
}

// GetOAuth2AuthorizationConsents returns the OAuth2AuthorizationConsents field value if set, zero value otherwise.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetOAuth2AuthorizationConsents() []Dhis2OAuth2AuthorizationConsent {
	if o == nil || IsNil(o.OAuth2AuthorizationConsents) {
		var ret []Dhis2OAuth2AuthorizationConsent
		return ret
	}
	return o.OAuth2AuthorizationConsents
}

// GetOAuth2AuthorizationConsentsOk returns a tuple with the OAuth2AuthorizationConsents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) GetOAuth2AuthorizationConsentsOk() ([]Dhis2OAuth2AuthorizationConsent, bool) {
	if o == nil || IsNil(o.OAuth2AuthorizationConsents) {
		return nil, false
	}
	return o.OAuth2AuthorizationConsents, true
}

// HasOAuth2AuthorizationConsents returns a boolean if a field has been set.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) HasOAuth2AuthorizationConsents() bool {
	if o != nil && !IsNil(o.OAuth2AuthorizationConsents) {
		return true
	}

	return false
}

// SetOAuth2AuthorizationConsents gets a reference to the given []Dhis2OAuth2AuthorizationConsent and assigns it to the OAuth2AuthorizationConsents field.
func (o *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) SetOAuth2AuthorizationConsents(v []Dhis2OAuth2AuthorizationConsent) {
	o.OAuth2AuthorizationConsents = v
}

func (o OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Pager) {
		toSerialize["pager"] = o.Pager
	}
	if !IsNil(o.OAuth2AuthorizationConsents) {
		toSerialize["oAuth2AuthorizationConsents"] = o.OAuth2AuthorizationConsents
	}
	return toSerialize, nil
}

type NullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf struct {
	value *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	isSet bool
}

func (v NullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) Get() *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	return v.value
}

func (v *NullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) Set(val *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf(val *OAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) *NullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf {
	return &NullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf{value: val, isSet: true}
}

func (v NullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuth2AuthorizationConsentGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
