/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.40
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProgramIndicatorProgramIndicatorGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProgramIndicatorProgramIndicatorGroupsInner{}

// ProgramIndicatorProgramIndicatorGroupsInner A UID reference to a ProgramIndicatorGroup   (Java name `org.hisp.dhis.program.ProgramIndicatorGroup`)
type ProgramIndicatorProgramIndicatorGroupsInner struct {
	Id string `json:"id"`
}

type _ProgramIndicatorProgramIndicatorGroupsInner ProgramIndicatorProgramIndicatorGroupsInner

// NewProgramIndicatorProgramIndicatorGroupsInner instantiates a new ProgramIndicatorProgramIndicatorGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgramIndicatorProgramIndicatorGroupsInner(id string) *ProgramIndicatorProgramIndicatorGroupsInner {
	this := ProgramIndicatorProgramIndicatorGroupsInner{}
	this.Id = id
	return &this
}

// NewProgramIndicatorProgramIndicatorGroupsInnerWithDefaults instantiates a new ProgramIndicatorProgramIndicatorGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgramIndicatorProgramIndicatorGroupsInnerWithDefaults() *ProgramIndicatorProgramIndicatorGroupsInner {
	this := ProgramIndicatorProgramIndicatorGroupsInner{}
	return &this
}

// GetId returns the Id field value
func (o *ProgramIndicatorProgramIndicatorGroupsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProgramIndicatorProgramIndicatorGroupsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProgramIndicatorProgramIndicatorGroupsInner) SetId(v string) {
	o.Id = v
}

func (o ProgramIndicatorProgramIndicatorGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProgramIndicatorProgramIndicatorGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ProgramIndicatorProgramIndicatorGroupsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProgramIndicatorProgramIndicatorGroupsInner := _ProgramIndicatorProgramIndicatorGroupsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProgramIndicatorProgramIndicatorGroupsInner)

	if err != nil {
		return err
	}

	*o = ProgramIndicatorProgramIndicatorGroupsInner(varProgramIndicatorProgramIndicatorGroupsInner)

	return err
}

type NullableProgramIndicatorProgramIndicatorGroupsInner struct {
	value *ProgramIndicatorProgramIndicatorGroupsInner
	isSet bool
}

func (v NullableProgramIndicatorProgramIndicatorGroupsInner) Get() *ProgramIndicatorProgramIndicatorGroupsInner {
	return v.value
}

func (v *NullableProgramIndicatorProgramIndicatorGroupsInner) Set(val *ProgramIndicatorProgramIndicatorGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProgramIndicatorProgramIndicatorGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProgramIndicatorProgramIndicatorGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgramIndicatorProgramIndicatorGroupsInner(val *ProgramIndicatorProgramIndicatorGroupsInner) *NullableProgramIndicatorProgramIndicatorGroupsInner {
	return &NullableProgramIndicatorProgramIndicatorGroupsInner{value: val, isSet: true}
}

func (v NullableProgramIndicatorProgramIndicatorGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgramIndicatorProgramIndicatorGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
