/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ProgramParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProgramParams{}

// ProgramParams struct for ProgramParams
type ProgramParams struct {
	AccessLevel                        AccessLevel                                         `json:"accessLevel"`
	AttributeValues                    []AttributeValueParams                              `json:"attributeValues,omitempty"`
	CategoryCombo                      *CategoryComboParams                                `json:"categoryCombo,omitempty"`
	CategoryMappings                   []ProgramCategoryMapping                            `json:"categoryMappings,omitempty"`
	Code                               *string                                             `json:"code,omitempty"`
	CompleteEventsExpiryDays           int32                                               `json:"completeEventsExpiryDays"`
	Created                            *time.Time                                          `json:"created,omitempty"`
	CreatedBy                          *AggregateDataExchangeParamsCreatedBy               `json:"createdBy,omitempty"`
	DataEntryForm                      *DataSetParamsDataEntryForm                         `json:"dataEntryForm,omitempty"`
	Description                        *string                                             `json:"description,omitempty"`
	DisplayDescription                 *string                                             `json:"displayDescription,omitempty"`
	DisplayEnrollmentDateLabel         *string                                             `json:"displayEnrollmentDateLabel,omitempty"`
	DisplayEnrollmentLabel             *string                                             `json:"displayEnrollmentLabel,omitempty"`
	DisplayEventLabel                  *string                                             `json:"displayEventLabel,omitempty"`
	DisplayFollowUpLabel               *string                                             `json:"displayFollowUpLabel,omitempty"`
	DisplayFormName                    *string                                             `json:"displayFormName,omitempty"`
	DisplayFrontPageList               *bool                                               `json:"displayFrontPageList,omitempty"`
	DisplayIncidentDate                *bool                                               `json:"displayIncidentDate,omitempty"`
	DisplayIncidentDateLabel           *string                                             `json:"displayIncidentDateLabel,omitempty"`
	DisplayName                        *string                                             `json:"displayName,omitempty"`
	DisplayNoteLabel                   *string                                             `json:"displayNoteLabel,omitempty"`
	DisplayOrgUnitLabel                *string                                             `json:"displayOrgUnitLabel,omitempty"`
	DisplayProgramStageLabel           *string                                             `json:"displayProgramStageLabel,omitempty"`
	DisplayRelationshipLabel           *string                                             `json:"displayRelationshipLabel,omitempty"`
	DisplayShortName                   *string                                             `json:"displayShortName,omitempty"`
	DisplayTrackedEntityAttributeLabel *string                                             `json:"displayTrackedEntityAttributeLabel,omitempty"`
	EnrollmentDateLabel                *string                                             `json:"enrollmentDateLabel,omitempty"`
	EnrollmentLabel                    *string                                             `json:"enrollmentLabel,omitempty"`
	EventLabel                         *string                                             `json:"eventLabel,omitempty"`
	ExpiryDays                         int32                                               `json:"expiryDays"`
	ExpiryPeriodType                   *string                                             `json:"expiryPeriodType,omitempty"`
	Favorite                           *bool                                               `json:"favorite,omitempty"`
	Favorites                          []string                                            `json:"favorites,omitempty"`
	FeatureType                        FeatureType                                         `json:"featureType"`
	FollowUpLabel                      *string                                             `json:"followUpLabel,omitempty"`
	FormName                           *string                                             `json:"formName,omitempty"`
	Id                                 *string                                             `json:"id,omitempty"`
	IgnoreOverdueEvents                *bool                                               `json:"ignoreOverdueEvents,omitempty"`
	IncidentDateLabel                  *string                                             `json:"incidentDateLabel,omitempty"`
	LastUpdated                        *time.Time                                          `json:"lastUpdated,omitempty"`
	LastUpdatedBy                      *AggregateDataExchangeParamsCreatedBy               `json:"lastUpdatedBy,omitempty"`
	MaxTeiCountToReturn                int32                                               `json:"maxTeiCountToReturn"`
	MinAttributesRequiredToSearch      int32                                               `json:"minAttributesRequiredToSearch"`
	Name                               *string                                             `json:"name,omitempty"`
	NoteLabel                          *string                                             `json:"noteLabel,omitempty"`
	NotificationTemplates              []ProgramParamsNotificationTemplatesInner           `json:"notificationTemplates,omitempty"`
	OnlyEnrollOnce                     *bool                                               `json:"onlyEnrollOnce,omitempty"`
	OpenDaysAfterCoEndDate             int32                                               `json:"openDaysAfterCoEndDate"`
	OrgUnitLabel                       *string                                             `json:"orgUnitLabel,omitempty"`
	OrganisationUnits                  []CategoryOptionParamsOrganisationUnitsInner        `json:"organisationUnits,omitempty"`
	ProgramIndicators                  []ProgramIndicatorGroupParamsProgramIndicatorsInner `json:"programIndicators,omitempty"`
	ProgramRuleVariables               []ProgramParamsProgramRuleVariablesInner            `json:"programRuleVariables,omitempty"`
	ProgramSections                    []ProgramParamsProgramSectionsInner                 `json:"programSections,omitempty"`
	ProgramStageLabel                  *string                                             `json:"programStageLabel,omitempty"`
	ProgramStages                      []ProgramParamsProgramStagesInner                   `json:"programStages,omitempty"`
	ProgramTrackedEntityAttributes     []ProgramTrackedEntityAttributeParams               `json:"programTrackedEntityAttributes,omitempty"`
	ProgramType                        ProgramType                                         `json:"programType"`
	Registration                       *bool                                               `json:"registration,omitempty"`
	RelatedProgram                     *ProgramParams                                      `json:"relatedProgram,omitempty"`
	RelationshipLabel                  *string                                             `json:"relationshipLabel,omitempty"`
	SelectEnrollmentDatesInFuture      *bool                                               `json:"selectEnrollmentDatesInFuture,omitempty"`
	SelectIncidentDatesInFuture        *bool                                               `json:"selectIncidentDatesInFuture,omitempty"`
	Sharing                            *Sharing                                            `json:"sharing,omitempty"`
	ShortName                          *string                                             `json:"shortName,omitempty"`
	SkipOffline                        *bool                                               `json:"skipOffline,omitempty"`
	Style                              *ObjectStyle                                        `json:"style,omitempty"`
	TrackedEntityAttributeLabel        *string                                             `json:"trackedEntityAttributeLabel,omitempty"`
	TrackedEntityType                  *MapViewParamsTrackedEntityType                     `json:"trackedEntityType,omitempty"`
	Translations                       []Translation                                       `json:"translations,omitempty"`
	UseFirstStageDuringRegistration    *bool                                               `json:"useFirstStageDuringRegistration,omitempty"`
	UserRoles                          []ProgramParamsUserRolesInner                       `json:"userRoles,omitempty"`
	Version                            int32                                               `json:"version"`
	WithoutRegistration                *bool                                               `json:"withoutRegistration,omitempty"`
}

type _ProgramParams ProgramParams

// NewProgramParams instantiates a new ProgramParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgramParams(accessLevel AccessLevel, completeEventsExpiryDays int32, expiryDays int32, featureType FeatureType, maxTeiCountToReturn int32, minAttributesRequiredToSearch int32, openDaysAfterCoEndDate int32, programType ProgramType, version int32) *ProgramParams {
	this := ProgramParams{}
	this.AccessLevel = accessLevel
	this.CompleteEventsExpiryDays = completeEventsExpiryDays
	this.ExpiryDays = expiryDays
	this.FeatureType = featureType
	this.MaxTeiCountToReturn = maxTeiCountToReturn
	this.MinAttributesRequiredToSearch = minAttributesRequiredToSearch
	this.OpenDaysAfterCoEndDate = openDaysAfterCoEndDate
	this.ProgramType = programType
	this.Version = version
	return &this
}

// NewProgramParamsWithDefaults instantiates a new ProgramParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgramParamsWithDefaults() *ProgramParams {
	this := ProgramParams{}
	return &this
}

// GetAccessLevel returns the AccessLevel field value
func (o *ProgramParams) GetAccessLevel() AccessLevel {
	if o == nil {
		var ret AccessLevel
		return ret
	}

	return o.AccessLevel
}

// GetAccessLevelOk returns a tuple with the AccessLevel field value
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetAccessLevelOk() (*AccessLevel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessLevel, true
}

// SetAccessLevel sets field value
func (o *ProgramParams) SetAccessLevel(v AccessLevel) {
	o.AccessLevel = v
}

// GetAttributeValues returns the AttributeValues field value if set, zero value otherwise.
func (o *ProgramParams) GetAttributeValues() []AttributeValueParams {
	if o == nil || IsNil(o.AttributeValues) {
		var ret []AttributeValueParams
		return ret
	}
	return o.AttributeValues
}

// GetAttributeValuesOk returns a tuple with the AttributeValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetAttributeValuesOk() ([]AttributeValueParams, bool) {
	if o == nil || IsNil(o.AttributeValues) {
		return nil, false
	}
	return o.AttributeValues, true
}

// HasAttributeValues returns a boolean if a field has been set.
func (o *ProgramParams) HasAttributeValues() bool {
	if o != nil && !IsNil(o.AttributeValues) {
		return true
	}

	return false
}

// SetAttributeValues gets a reference to the given []AttributeValueParams and assigns it to the AttributeValues field.
func (o *ProgramParams) SetAttributeValues(v []AttributeValueParams) {
	o.AttributeValues = v
}

// GetCategoryCombo returns the CategoryCombo field value if set, zero value otherwise.
func (o *ProgramParams) GetCategoryCombo() CategoryComboParams {
	if o == nil || IsNil(o.CategoryCombo) {
		var ret CategoryComboParams
		return ret
	}
	return *o.CategoryCombo
}

// GetCategoryComboOk returns a tuple with the CategoryCombo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetCategoryComboOk() (*CategoryComboParams, bool) {
	if o == nil || IsNil(o.CategoryCombo) {
		return nil, false
	}
	return o.CategoryCombo, true
}

// HasCategoryCombo returns a boolean if a field has been set.
func (o *ProgramParams) HasCategoryCombo() bool {
	if o != nil && !IsNil(o.CategoryCombo) {
		return true
	}

	return false
}

// SetCategoryCombo gets a reference to the given CategoryComboParams and assigns it to the CategoryCombo field.
func (o *ProgramParams) SetCategoryCombo(v CategoryComboParams) {
	o.CategoryCombo = &v
}

// GetCategoryMappings returns the CategoryMappings field value if set, zero value otherwise.
func (o *ProgramParams) GetCategoryMappings() []ProgramCategoryMapping {
	if o == nil || IsNil(o.CategoryMappings) {
		var ret []ProgramCategoryMapping
		return ret
	}
	return o.CategoryMappings
}

// GetCategoryMappingsOk returns a tuple with the CategoryMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetCategoryMappingsOk() ([]ProgramCategoryMapping, bool) {
	if o == nil || IsNil(o.CategoryMappings) {
		return nil, false
	}
	return o.CategoryMappings, true
}

// HasCategoryMappings returns a boolean if a field has been set.
func (o *ProgramParams) HasCategoryMappings() bool {
	if o != nil && !IsNil(o.CategoryMappings) {
		return true
	}

	return false
}

// SetCategoryMappings gets a reference to the given []ProgramCategoryMapping and assigns it to the CategoryMappings field.
func (o *ProgramParams) SetCategoryMappings(v []ProgramCategoryMapping) {
	o.CategoryMappings = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ProgramParams) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ProgramParams) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ProgramParams) SetCode(v string) {
	o.Code = &v
}

// GetCompleteEventsExpiryDays returns the CompleteEventsExpiryDays field value
func (o *ProgramParams) GetCompleteEventsExpiryDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CompleteEventsExpiryDays
}

// GetCompleteEventsExpiryDaysOk returns a tuple with the CompleteEventsExpiryDays field value
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetCompleteEventsExpiryDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompleteEventsExpiryDays, true
}

// SetCompleteEventsExpiryDays sets field value
func (o *ProgramParams) SetCompleteEventsExpiryDays(v int32) {
	o.CompleteEventsExpiryDays = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ProgramParams) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ProgramParams) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ProgramParams) SetCreated(v time.Time) {
	o.Created = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *ProgramParams) GetCreatedBy() AggregateDataExchangeParamsCreatedBy {
	if o == nil || IsNil(o.CreatedBy) {
		var ret AggregateDataExchangeParamsCreatedBy
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetCreatedByOk() (*AggregateDataExchangeParamsCreatedBy, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *ProgramParams) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given AggregateDataExchangeParamsCreatedBy and assigns it to the CreatedBy field.
func (o *ProgramParams) SetCreatedBy(v AggregateDataExchangeParamsCreatedBy) {
	o.CreatedBy = &v
}

// GetDataEntryForm returns the DataEntryForm field value if set, zero value otherwise.
func (o *ProgramParams) GetDataEntryForm() DataSetParamsDataEntryForm {
	if o == nil || IsNil(o.DataEntryForm) {
		var ret DataSetParamsDataEntryForm
		return ret
	}
	return *o.DataEntryForm
}

// GetDataEntryFormOk returns a tuple with the DataEntryForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDataEntryFormOk() (*DataSetParamsDataEntryForm, bool) {
	if o == nil || IsNil(o.DataEntryForm) {
		return nil, false
	}
	return o.DataEntryForm, true
}

// HasDataEntryForm returns a boolean if a field has been set.
func (o *ProgramParams) HasDataEntryForm() bool {
	if o != nil && !IsNil(o.DataEntryForm) {
		return true
	}

	return false
}

// SetDataEntryForm gets a reference to the given DataSetParamsDataEntryForm and assigns it to the DataEntryForm field.
func (o *ProgramParams) SetDataEntryForm(v DataSetParamsDataEntryForm) {
	o.DataEntryForm = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProgramParams) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProgramParams) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProgramParams) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayDescription returns the DisplayDescription field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayDescription() string {
	if o == nil || IsNil(o.DisplayDescription) {
		var ret string
		return ret
	}
	return *o.DisplayDescription
}

// GetDisplayDescriptionOk returns a tuple with the DisplayDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayDescription) {
		return nil, false
	}
	return o.DisplayDescription, true
}

// HasDisplayDescription returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayDescription() bool {
	if o != nil && !IsNil(o.DisplayDescription) {
		return true
	}

	return false
}

// SetDisplayDescription gets a reference to the given string and assigns it to the DisplayDescription field.
func (o *ProgramParams) SetDisplayDescription(v string) {
	o.DisplayDescription = &v
}

// GetDisplayEnrollmentDateLabel returns the DisplayEnrollmentDateLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayEnrollmentDateLabel() string {
	if o == nil || IsNil(o.DisplayEnrollmentDateLabel) {
		var ret string
		return ret
	}
	return *o.DisplayEnrollmentDateLabel
}

// GetDisplayEnrollmentDateLabelOk returns a tuple with the DisplayEnrollmentDateLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayEnrollmentDateLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayEnrollmentDateLabel) {
		return nil, false
	}
	return o.DisplayEnrollmentDateLabel, true
}

// HasDisplayEnrollmentDateLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayEnrollmentDateLabel() bool {
	if o != nil && !IsNil(o.DisplayEnrollmentDateLabel) {
		return true
	}

	return false
}

// SetDisplayEnrollmentDateLabel gets a reference to the given string and assigns it to the DisplayEnrollmentDateLabel field.
func (o *ProgramParams) SetDisplayEnrollmentDateLabel(v string) {
	o.DisplayEnrollmentDateLabel = &v
}

// GetDisplayEnrollmentLabel returns the DisplayEnrollmentLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayEnrollmentLabel() string {
	if o == nil || IsNil(o.DisplayEnrollmentLabel) {
		var ret string
		return ret
	}
	return *o.DisplayEnrollmentLabel
}

// GetDisplayEnrollmentLabelOk returns a tuple with the DisplayEnrollmentLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayEnrollmentLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayEnrollmentLabel) {
		return nil, false
	}
	return o.DisplayEnrollmentLabel, true
}

// HasDisplayEnrollmentLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayEnrollmentLabel() bool {
	if o != nil && !IsNil(o.DisplayEnrollmentLabel) {
		return true
	}

	return false
}

// SetDisplayEnrollmentLabel gets a reference to the given string and assigns it to the DisplayEnrollmentLabel field.
func (o *ProgramParams) SetDisplayEnrollmentLabel(v string) {
	o.DisplayEnrollmentLabel = &v
}

// GetDisplayEventLabel returns the DisplayEventLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayEventLabel() string {
	if o == nil || IsNil(o.DisplayEventLabel) {
		var ret string
		return ret
	}
	return *o.DisplayEventLabel
}

// GetDisplayEventLabelOk returns a tuple with the DisplayEventLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayEventLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayEventLabel) {
		return nil, false
	}
	return o.DisplayEventLabel, true
}

// HasDisplayEventLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayEventLabel() bool {
	if o != nil && !IsNil(o.DisplayEventLabel) {
		return true
	}

	return false
}

// SetDisplayEventLabel gets a reference to the given string and assigns it to the DisplayEventLabel field.
func (o *ProgramParams) SetDisplayEventLabel(v string) {
	o.DisplayEventLabel = &v
}

// GetDisplayFollowUpLabel returns the DisplayFollowUpLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayFollowUpLabel() string {
	if o == nil || IsNil(o.DisplayFollowUpLabel) {
		var ret string
		return ret
	}
	return *o.DisplayFollowUpLabel
}

// GetDisplayFollowUpLabelOk returns a tuple with the DisplayFollowUpLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayFollowUpLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayFollowUpLabel) {
		return nil, false
	}
	return o.DisplayFollowUpLabel, true
}

// HasDisplayFollowUpLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayFollowUpLabel() bool {
	if o != nil && !IsNil(o.DisplayFollowUpLabel) {
		return true
	}

	return false
}

// SetDisplayFollowUpLabel gets a reference to the given string and assigns it to the DisplayFollowUpLabel field.
func (o *ProgramParams) SetDisplayFollowUpLabel(v string) {
	o.DisplayFollowUpLabel = &v
}

// GetDisplayFormName returns the DisplayFormName field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayFormName() string {
	if o == nil || IsNil(o.DisplayFormName) {
		var ret string
		return ret
	}
	return *o.DisplayFormName
}

// GetDisplayFormNameOk returns a tuple with the DisplayFormName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayFormNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayFormName) {
		return nil, false
	}
	return o.DisplayFormName, true
}

// HasDisplayFormName returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayFormName() bool {
	if o != nil && !IsNil(o.DisplayFormName) {
		return true
	}

	return false
}

// SetDisplayFormName gets a reference to the given string and assigns it to the DisplayFormName field.
func (o *ProgramParams) SetDisplayFormName(v string) {
	o.DisplayFormName = &v
}

// GetDisplayFrontPageList returns the DisplayFrontPageList field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayFrontPageList() bool {
	if o == nil || IsNil(o.DisplayFrontPageList) {
		var ret bool
		return ret
	}
	return *o.DisplayFrontPageList
}

// GetDisplayFrontPageListOk returns a tuple with the DisplayFrontPageList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayFrontPageListOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplayFrontPageList) {
		return nil, false
	}
	return o.DisplayFrontPageList, true
}

// HasDisplayFrontPageList returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayFrontPageList() bool {
	if o != nil && !IsNil(o.DisplayFrontPageList) {
		return true
	}

	return false
}

// SetDisplayFrontPageList gets a reference to the given bool and assigns it to the DisplayFrontPageList field.
func (o *ProgramParams) SetDisplayFrontPageList(v bool) {
	o.DisplayFrontPageList = &v
}

// GetDisplayIncidentDate returns the DisplayIncidentDate field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayIncidentDate() bool {
	if o == nil || IsNil(o.DisplayIncidentDate) {
		var ret bool
		return ret
	}
	return *o.DisplayIncidentDate
}

// GetDisplayIncidentDateOk returns a tuple with the DisplayIncidentDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayIncidentDateOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplayIncidentDate) {
		return nil, false
	}
	return o.DisplayIncidentDate, true
}

// HasDisplayIncidentDate returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayIncidentDate() bool {
	if o != nil && !IsNil(o.DisplayIncidentDate) {
		return true
	}

	return false
}

// SetDisplayIncidentDate gets a reference to the given bool and assigns it to the DisplayIncidentDate field.
func (o *ProgramParams) SetDisplayIncidentDate(v bool) {
	o.DisplayIncidentDate = &v
}

// GetDisplayIncidentDateLabel returns the DisplayIncidentDateLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayIncidentDateLabel() string {
	if o == nil || IsNil(o.DisplayIncidentDateLabel) {
		var ret string
		return ret
	}
	return *o.DisplayIncidentDateLabel
}

// GetDisplayIncidentDateLabelOk returns a tuple with the DisplayIncidentDateLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayIncidentDateLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayIncidentDateLabel) {
		return nil, false
	}
	return o.DisplayIncidentDateLabel, true
}

// HasDisplayIncidentDateLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayIncidentDateLabel() bool {
	if o != nil && !IsNil(o.DisplayIncidentDateLabel) {
		return true
	}

	return false
}

// SetDisplayIncidentDateLabel gets a reference to the given string and assigns it to the DisplayIncidentDateLabel field.
func (o *ProgramParams) SetDisplayIncidentDateLabel(v string) {
	o.DisplayIncidentDateLabel = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ProgramParams) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDisplayNoteLabel returns the DisplayNoteLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayNoteLabel() string {
	if o == nil || IsNil(o.DisplayNoteLabel) {
		var ret string
		return ret
	}
	return *o.DisplayNoteLabel
}

// GetDisplayNoteLabelOk returns a tuple with the DisplayNoteLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayNoteLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayNoteLabel) {
		return nil, false
	}
	return o.DisplayNoteLabel, true
}

// HasDisplayNoteLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayNoteLabel() bool {
	if o != nil && !IsNil(o.DisplayNoteLabel) {
		return true
	}

	return false
}

// SetDisplayNoteLabel gets a reference to the given string and assigns it to the DisplayNoteLabel field.
func (o *ProgramParams) SetDisplayNoteLabel(v string) {
	o.DisplayNoteLabel = &v
}

// GetDisplayOrgUnitLabel returns the DisplayOrgUnitLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayOrgUnitLabel() string {
	if o == nil || IsNil(o.DisplayOrgUnitLabel) {
		var ret string
		return ret
	}
	return *o.DisplayOrgUnitLabel
}

// GetDisplayOrgUnitLabelOk returns a tuple with the DisplayOrgUnitLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayOrgUnitLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayOrgUnitLabel) {
		return nil, false
	}
	return o.DisplayOrgUnitLabel, true
}

// HasDisplayOrgUnitLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayOrgUnitLabel() bool {
	if o != nil && !IsNil(o.DisplayOrgUnitLabel) {
		return true
	}

	return false
}

// SetDisplayOrgUnitLabel gets a reference to the given string and assigns it to the DisplayOrgUnitLabel field.
func (o *ProgramParams) SetDisplayOrgUnitLabel(v string) {
	o.DisplayOrgUnitLabel = &v
}

// GetDisplayProgramStageLabel returns the DisplayProgramStageLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayProgramStageLabel() string {
	if o == nil || IsNil(o.DisplayProgramStageLabel) {
		var ret string
		return ret
	}
	return *o.DisplayProgramStageLabel
}

// GetDisplayProgramStageLabelOk returns a tuple with the DisplayProgramStageLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayProgramStageLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayProgramStageLabel) {
		return nil, false
	}
	return o.DisplayProgramStageLabel, true
}

// HasDisplayProgramStageLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayProgramStageLabel() bool {
	if o != nil && !IsNil(o.DisplayProgramStageLabel) {
		return true
	}

	return false
}

// SetDisplayProgramStageLabel gets a reference to the given string and assigns it to the DisplayProgramStageLabel field.
func (o *ProgramParams) SetDisplayProgramStageLabel(v string) {
	o.DisplayProgramStageLabel = &v
}

// GetDisplayRelationshipLabel returns the DisplayRelationshipLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayRelationshipLabel() string {
	if o == nil || IsNil(o.DisplayRelationshipLabel) {
		var ret string
		return ret
	}
	return *o.DisplayRelationshipLabel
}

// GetDisplayRelationshipLabelOk returns a tuple with the DisplayRelationshipLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayRelationshipLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayRelationshipLabel) {
		return nil, false
	}
	return o.DisplayRelationshipLabel, true
}

// HasDisplayRelationshipLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayRelationshipLabel() bool {
	if o != nil && !IsNil(o.DisplayRelationshipLabel) {
		return true
	}

	return false
}

// SetDisplayRelationshipLabel gets a reference to the given string and assigns it to the DisplayRelationshipLabel field.
func (o *ProgramParams) SetDisplayRelationshipLabel(v string) {
	o.DisplayRelationshipLabel = &v
}

// GetDisplayShortName returns the DisplayShortName field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayShortName() string {
	if o == nil || IsNil(o.DisplayShortName) {
		var ret string
		return ret
	}
	return *o.DisplayShortName
}

// GetDisplayShortNameOk returns a tuple with the DisplayShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayShortNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayShortName) {
		return nil, false
	}
	return o.DisplayShortName, true
}

// HasDisplayShortName returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayShortName() bool {
	if o != nil && !IsNil(o.DisplayShortName) {
		return true
	}

	return false
}

// SetDisplayShortName gets a reference to the given string and assigns it to the DisplayShortName field.
func (o *ProgramParams) SetDisplayShortName(v string) {
	o.DisplayShortName = &v
}

// GetDisplayTrackedEntityAttributeLabel returns the DisplayTrackedEntityAttributeLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetDisplayTrackedEntityAttributeLabel() string {
	if o == nil || IsNil(o.DisplayTrackedEntityAttributeLabel) {
		var ret string
		return ret
	}
	return *o.DisplayTrackedEntityAttributeLabel
}

// GetDisplayTrackedEntityAttributeLabelOk returns a tuple with the DisplayTrackedEntityAttributeLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetDisplayTrackedEntityAttributeLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayTrackedEntityAttributeLabel) {
		return nil, false
	}
	return o.DisplayTrackedEntityAttributeLabel, true
}

// HasDisplayTrackedEntityAttributeLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasDisplayTrackedEntityAttributeLabel() bool {
	if o != nil && !IsNil(o.DisplayTrackedEntityAttributeLabel) {
		return true
	}

	return false
}

// SetDisplayTrackedEntityAttributeLabel gets a reference to the given string and assigns it to the DisplayTrackedEntityAttributeLabel field.
func (o *ProgramParams) SetDisplayTrackedEntityAttributeLabel(v string) {
	o.DisplayTrackedEntityAttributeLabel = &v
}

// GetEnrollmentDateLabel returns the EnrollmentDateLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetEnrollmentDateLabel() string {
	if o == nil || IsNil(o.EnrollmentDateLabel) {
		var ret string
		return ret
	}
	return *o.EnrollmentDateLabel
}

// GetEnrollmentDateLabelOk returns a tuple with the EnrollmentDateLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetEnrollmentDateLabelOk() (*string, bool) {
	if o == nil || IsNil(o.EnrollmentDateLabel) {
		return nil, false
	}
	return o.EnrollmentDateLabel, true
}

// HasEnrollmentDateLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasEnrollmentDateLabel() bool {
	if o != nil && !IsNil(o.EnrollmentDateLabel) {
		return true
	}

	return false
}

// SetEnrollmentDateLabel gets a reference to the given string and assigns it to the EnrollmentDateLabel field.
func (o *ProgramParams) SetEnrollmentDateLabel(v string) {
	o.EnrollmentDateLabel = &v
}

// GetEnrollmentLabel returns the EnrollmentLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetEnrollmentLabel() string {
	if o == nil || IsNil(o.EnrollmentLabel) {
		var ret string
		return ret
	}
	return *o.EnrollmentLabel
}

// GetEnrollmentLabelOk returns a tuple with the EnrollmentLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetEnrollmentLabelOk() (*string, bool) {
	if o == nil || IsNil(o.EnrollmentLabel) {
		return nil, false
	}
	return o.EnrollmentLabel, true
}

// HasEnrollmentLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasEnrollmentLabel() bool {
	if o != nil && !IsNil(o.EnrollmentLabel) {
		return true
	}

	return false
}

// SetEnrollmentLabel gets a reference to the given string and assigns it to the EnrollmentLabel field.
func (o *ProgramParams) SetEnrollmentLabel(v string) {
	o.EnrollmentLabel = &v
}

// GetEventLabel returns the EventLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetEventLabel() string {
	if o == nil || IsNil(o.EventLabel) {
		var ret string
		return ret
	}
	return *o.EventLabel
}

// GetEventLabelOk returns a tuple with the EventLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetEventLabelOk() (*string, bool) {
	if o == nil || IsNil(o.EventLabel) {
		return nil, false
	}
	return o.EventLabel, true
}

// HasEventLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasEventLabel() bool {
	if o != nil && !IsNil(o.EventLabel) {
		return true
	}

	return false
}

// SetEventLabel gets a reference to the given string and assigns it to the EventLabel field.
func (o *ProgramParams) SetEventLabel(v string) {
	o.EventLabel = &v
}

// GetExpiryDays returns the ExpiryDays field value
func (o *ProgramParams) GetExpiryDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiryDays
}

// GetExpiryDaysOk returns a tuple with the ExpiryDays field value
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetExpiryDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiryDays, true
}

// SetExpiryDays sets field value
func (o *ProgramParams) SetExpiryDays(v int32) {
	o.ExpiryDays = v
}

// GetExpiryPeriodType returns the ExpiryPeriodType field value if set, zero value otherwise.
func (o *ProgramParams) GetExpiryPeriodType() string {
	if o == nil || IsNil(o.ExpiryPeriodType) {
		var ret string
		return ret
	}
	return *o.ExpiryPeriodType
}

// GetExpiryPeriodTypeOk returns a tuple with the ExpiryPeriodType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetExpiryPeriodTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiryPeriodType) {
		return nil, false
	}
	return o.ExpiryPeriodType, true
}

// HasExpiryPeriodType returns a boolean if a field has been set.
func (o *ProgramParams) HasExpiryPeriodType() bool {
	if o != nil && !IsNil(o.ExpiryPeriodType) {
		return true
	}

	return false
}

// SetExpiryPeriodType gets a reference to the given string and assigns it to the ExpiryPeriodType field.
func (o *ProgramParams) SetExpiryPeriodType(v string) {
	o.ExpiryPeriodType = &v
}

// GetFavorite returns the Favorite field value if set, zero value otherwise.
func (o *ProgramParams) GetFavorite() bool {
	if o == nil || IsNil(o.Favorite) {
		var ret bool
		return ret
	}
	return *o.Favorite
}

// GetFavoriteOk returns a tuple with the Favorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetFavoriteOk() (*bool, bool) {
	if o == nil || IsNil(o.Favorite) {
		return nil, false
	}
	return o.Favorite, true
}

// HasFavorite returns a boolean if a field has been set.
func (o *ProgramParams) HasFavorite() bool {
	if o != nil && !IsNil(o.Favorite) {
		return true
	}

	return false
}

// SetFavorite gets a reference to the given bool and assigns it to the Favorite field.
func (o *ProgramParams) SetFavorite(v bool) {
	o.Favorite = &v
}

// GetFavorites returns the Favorites field value if set, zero value otherwise.
func (o *ProgramParams) GetFavorites() []string {
	if o == nil || IsNil(o.Favorites) {
		var ret []string
		return ret
	}
	return o.Favorites
}

// GetFavoritesOk returns a tuple with the Favorites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetFavoritesOk() ([]string, bool) {
	if o == nil || IsNil(o.Favorites) {
		return nil, false
	}
	return o.Favorites, true
}

// HasFavorites returns a boolean if a field has been set.
func (o *ProgramParams) HasFavorites() bool {
	if o != nil && !IsNil(o.Favorites) {
		return true
	}

	return false
}

// SetFavorites gets a reference to the given []string and assigns it to the Favorites field.
func (o *ProgramParams) SetFavorites(v []string) {
	o.Favorites = v
}

// GetFeatureType returns the FeatureType field value
func (o *ProgramParams) GetFeatureType() FeatureType {
	if o == nil {
		var ret FeatureType
		return ret
	}

	return o.FeatureType
}

// GetFeatureTypeOk returns a tuple with the FeatureType field value
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetFeatureTypeOk() (*FeatureType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeatureType, true
}

// SetFeatureType sets field value
func (o *ProgramParams) SetFeatureType(v FeatureType) {
	o.FeatureType = v
}

// GetFollowUpLabel returns the FollowUpLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetFollowUpLabel() string {
	if o == nil || IsNil(o.FollowUpLabel) {
		var ret string
		return ret
	}
	return *o.FollowUpLabel
}

// GetFollowUpLabelOk returns a tuple with the FollowUpLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetFollowUpLabelOk() (*string, bool) {
	if o == nil || IsNil(o.FollowUpLabel) {
		return nil, false
	}
	return o.FollowUpLabel, true
}

// HasFollowUpLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasFollowUpLabel() bool {
	if o != nil && !IsNil(o.FollowUpLabel) {
		return true
	}

	return false
}

// SetFollowUpLabel gets a reference to the given string and assigns it to the FollowUpLabel field.
func (o *ProgramParams) SetFollowUpLabel(v string) {
	o.FollowUpLabel = &v
}

// GetFormName returns the FormName field value if set, zero value otherwise.
func (o *ProgramParams) GetFormName() string {
	if o == nil || IsNil(o.FormName) {
		var ret string
		return ret
	}
	return *o.FormName
}

// GetFormNameOk returns a tuple with the FormName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetFormNameOk() (*string, bool) {
	if o == nil || IsNil(o.FormName) {
		return nil, false
	}
	return o.FormName, true
}

// HasFormName returns a boolean if a field has been set.
func (o *ProgramParams) HasFormName() bool {
	if o != nil && !IsNil(o.FormName) {
		return true
	}

	return false
}

// SetFormName gets a reference to the given string and assigns it to the FormName field.
func (o *ProgramParams) SetFormName(v string) {
	o.FormName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProgramParams) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProgramParams) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProgramParams) SetId(v string) {
	o.Id = &v
}

// GetIgnoreOverdueEvents returns the IgnoreOverdueEvents field value if set, zero value otherwise.
func (o *ProgramParams) GetIgnoreOverdueEvents() bool {
	if o == nil || IsNil(o.IgnoreOverdueEvents) {
		var ret bool
		return ret
	}
	return *o.IgnoreOverdueEvents
}

// GetIgnoreOverdueEventsOk returns a tuple with the IgnoreOverdueEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetIgnoreOverdueEventsOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreOverdueEvents) {
		return nil, false
	}
	return o.IgnoreOverdueEvents, true
}

// HasIgnoreOverdueEvents returns a boolean if a field has been set.
func (o *ProgramParams) HasIgnoreOverdueEvents() bool {
	if o != nil && !IsNil(o.IgnoreOverdueEvents) {
		return true
	}

	return false
}

// SetIgnoreOverdueEvents gets a reference to the given bool and assigns it to the IgnoreOverdueEvents field.
func (o *ProgramParams) SetIgnoreOverdueEvents(v bool) {
	o.IgnoreOverdueEvents = &v
}

// GetIncidentDateLabel returns the IncidentDateLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetIncidentDateLabel() string {
	if o == nil || IsNil(o.IncidentDateLabel) {
		var ret string
		return ret
	}
	return *o.IncidentDateLabel
}

// GetIncidentDateLabelOk returns a tuple with the IncidentDateLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetIncidentDateLabelOk() (*string, bool) {
	if o == nil || IsNil(o.IncidentDateLabel) {
		return nil, false
	}
	return o.IncidentDateLabel, true
}

// HasIncidentDateLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasIncidentDateLabel() bool {
	if o != nil && !IsNil(o.IncidentDateLabel) {
		return true
	}

	return false
}

// SetIncidentDateLabel gets a reference to the given string and assigns it to the IncidentDateLabel field.
func (o *ProgramParams) SetIncidentDateLabel(v string) {
	o.IncidentDateLabel = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *ProgramParams) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *ProgramParams) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given time.Time and assigns it to the LastUpdated field.
func (o *ProgramParams) SetLastUpdated(v time.Time) {
	o.LastUpdated = &v
}

// GetLastUpdatedBy returns the LastUpdatedBy field value if set, zero value otherwise.
func (o *ProgramParams) GetLastUpdatedBy() AggregateDataExchangeParamsCreatedBy {
	if o == nil || IsNil(o.LastUpdatedBy) {
		var ret AggregateDataExchangeParamsCreatedBy
		return ret
	}
	return *o.LastUpdatedBy
}

// GetLastUpdatedByOk returns a tuple with the LastUpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetLastUpdatedByOk() (*AggregateDataExchangeParamsCreatedBy, bool) {
	if o == nil || IsNil(o.LastUpdatedBy) {
		return nil, false
	}
	return o.LastUpdatedBy, true
}

// HasLastUpdatedBy returns a boolean if a field has been set.
func (o *ProgramParams) HasLastUpdatedBy() bool {
	if o != nil && !IsNil(o.LastUpdatedBy) {
		return true
	}

	return false
}

// SetLastUpdatedBy gets a reference to the given AggregateDataExchangeParamsCreatedBy and assigns it to the LastUpdatedBy field.
func (o *ProgramParams) SetLastUpdatedBy(v AggregateDataExchangeParamsCreatedBy) {
	o.LastUpdatedBy = &v
}

// GetMaxTeiCountToReturn returns the MaxTeiCountToReturn field value
func (o *ProgramParams) GetMaxTeiCountToReturn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxTeiCountToReturn
}

// GetMaxTeiCountToReturnOk returns a tuple with the MaxTeiCountToReturn field value
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetMaxTeiCountToReturnOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxTeiCountToReturn, true
}

// SetMaxTeiCountToReturn sets field value
func (o *ProgramParams) SetMaxTeiCountToReturn(v int32) {
	o.MaxTeiCountToReturn = v
}

// GetMinAttributesRequiredToSearch returns the MinAttributesRequiredToSearch field value
func (o *ProgramParams) GetMinAttributesRequiredToSearch() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinAttributesRequiredToSearch
}

// GetMinAttributesRequiredToSearchOk returns a tuple with the MinAttributesRequiredToSearch field value
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetMinAttributesRequiredToSearchOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinAttributesRequiredToSearch, true
}

// SetMinAttributesRequiredToSearch sets field value
func (o *ProgramParams) SetMinAttributesRequiredToSearch(v int32) {
	o.MinAttributesRequiredToSearch = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProgramParams) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProgramParams) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProgramParams) SetName(v string) {
	o.Name = &v
}

// GetNoteLabel returns the NoteLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetNoteLabel() string {
	if o == nil || IsNil(o.NoteLabel) {
		var ret string
		return ret
	}
	return *o.NoteLabel
}

// GetNoteLabelOk returns a tuple with the NoteLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetNoteLabelOk() (*string, bool) {
	if o == nil || IsNil(o.NoteLabel) {
		return nil, false
	}
	return o.NoteLabel, true
}

// HasNoteLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasNoteLabel() bool {
	if o != nil && !IsNil(o.NoteLabel) {
		return true
	}

	return false
}

// SetNoteLabel gets a reference to the given string and assigns it to the NoteLabel field.
func (o *ProgramParams) SetNoteLabel(v string) {
	o.NoteLabel = &v
}

// GetNotificationTemplates returns the NotificationTemplates field value if set, zero value otherwise.
func (o *ProgramParams) GetNotificationTemplates() []ProgramParamsNotificationTemplatesInner {
	if o == nil || IsNil(o.NotificationTemplates) {
		var ret []ProgramParamsNotificationTemplatesInner
		return ret
	}
	return o.NotificationTemplates
}

// GetNotificationTemplatesOk returns a tuple with the NotificationTemplates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetNotificationTemplatesOk() ([]ProgramParamsNotificationTemplatesInner, bool) {
	if o == nil || IsNil(o.NotificationTemplates) {
		return nil, false
	}
	return o.NotificationTemplates, true
}

// HasNotificationTemplates returns a boolean if a field has been set.
func (o *ProgramParams) HasNotificationTemplates() bool {
	if o != nil && !IsNil(o.NotificationTemplates) {
		return true
	}

	return false
}

// SetNotificationTemplates gets a reference to the given []ProgramParamsNotificationTemplatesInner and assigns it to the NotificationTemplates field.
func (o *ProgramParams) SetNotificationTemplates(v []ProgramParamsNotificationTemplatesInner) {
	o.NotificationTemplates = v
}

// GetOnlyEnrollOnce returns the OnlyEnrollOnce field value if set, zero value otherwise.
func (o *ProgramParams) GetOnlyEnrollOnce() bool {
	if o == nil || IsNil(o.OnlyEnrollOnce) {
		var ret bool
		return ret
	}
	return *o.OnlyEnrollOnce
}

// GetOnlyEnrollOnceOk returns a tuple with the OnlyEnrollOnce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetOnlyEnrollOnceOk() (*bool, bool) {
	if o == nil || IsNil(o.OnlyEnrollOnce) {
		return nil, false
	}
	return o.OnlyEnrollOnce, true
}

// HasOnlyEnrollOnce returns a boolean if a field has been set.
func (o *ProgramParams) HasOnlyEnrollOnce() bool {
	if o != nil && !IsNil(o.OnlyEnrollOnce) {
		return true
	}

	return false
}

// SetOnlyEnrollOnce gets a reference to the given bool and assigns it to the OnlyEnrollOnce field.
func (o *ProgramParams) SetOnlyEnrollOnce(v bool) {
	o.OnlyEnrollOnce = &v
}

// GetOpenDaysAfterCoEndDate returns the OpenDaysAfterCoEndDate field value
func (o *ProgramParams) GetOpenDaysAfterCoEndDate() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OpenDaysAfterCoEndDate
}

// GetOpenDaysAfterCoEndDateOk returns a tuple with the OpenDaysAfterCoEndDate field value
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetOpenDaysAfterCoEndDateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OpenDaysAfterCoEndDate, true
}

// SetOpenDaysAfterCoEndDate sets field value
func (o *ProgramParams) SetOpenDaysAfterCoEndDate(v int32) {
	o.OpenDaysAfterCoEndDate = v
}

// GetOrgUnitLabel returns the OrgUnitLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetOrgUnitLabel() string {
	if o == nil || IsNil(o.OrgUnitLabel) {
		var ret string
		return ret
	}
	return *o.OrgUnitLabel
}

// GetOrgUnitLabelOk returns a tuple with the OrgUnitLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetOrgUnitLabelOk() (*string, bool) {
	if o == nil || IsNil(o.OrgUnitLabel) {
		return nil, false
	}
	return o.OrgUnitLabel, true
}

// HasOrgUnitLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasOrgUnitLabel() bool {
	if o != nil && !IsNil(o.OrgUnitLabel) {
		return true
	}

	return false
}

// SetOrgUnitLabel gets a reference to the given string and assigns it to the OrgUnitLabel field.
func (o *ProgramParams) SetOrgUnitLabel(v string) {
	o.OrgUnitLabel = &v
}

// GetOrganisationUnits returns the OrganisationUnits field value if set, zero value otherwise.
func (o *ProgramParams) GetOrganisationUnits() []CategoryOptionParamsOrganisationUnitsInner {
	if o == nil || IsNil(o.OrganisationUnits) {
		var ret []CategoryOptionParamsOrganisationUnitsInner
		return ret
	}
	return o.OrganisationUnits
}

// GetOrganisationUnitsOk returns a tuple with the OrganisationUnits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetOrganisationUnitsOk() ([]CategoryOptionParamsOrganisationUnitsInner, bool) {
	if o == nil || IsNil(o.OrganisationUnits) {
		return nil, false
	}
	return o.OrganisationUnits, true
}

// HasOrganisationUnits returns a boolean if a field has been set.
func (o *ProgramParams) HasOrganisationUnits() bool {
	if o != nil && !IsNil(o.OrganisationUnits) {
		return true
	}

	return false
}

// SetOrganisationUnits gets a reference to the given []CategoryOptionParamsOrganisationUnitsInner and assigns it to the OrganisationUnits field.
func (o *ProgramParams) SetOrganisationUnits(v []CategoryOptionParamsOrganisationUnitsInner) {
	o.OrganisationUnits = v
}

// GetProgramIndicators returns the ProgramIndicators field value if set, zero value otherwise.
func (o *ProgramParams) GetProgramIndicators() []ProgramIndicatorGroupParamsProgramIndicatorsInner {
	if o == nil || IsNil(o.ProgramIndicators) {
		var ret []ProgramIndicatorGroupParamsProgramIndicatorsInner
		return ret
	}
	return o.ProgramIndicators
}

// GetProgramIndicatorsOk returns a tuple with the ProgramIndicators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetProgramIndicatorsOk() ([]ProgramIndicatorGroupParamsProgramIndicatorsInner, bool) {
	if o == nil || IsNil(o.ProgramIndicators) {
		return nil, false
	}
	return o.ProgramIndicators, true
}

// HasProgramIndicators returns a boolean if a field has been set.
func (o *ProgramParams) HasProgramIndicators() bool {
	if o != nil && !IsNil(o.ProgramIndicators) {
		return true
	}

	return false
}

// SetProgramIndicators gets a reference to the given []ProgramIndicatorGroupParamsProgramIndicatorsInner and assigns it to the ProgramIndicators field.
func (o *ProgramParams) SetProgramIndicators(v []ProgramIndicatorGroupParamsProgramIndicatorsInner) {
	o.ProgramIndicators = v
}

// GetProgramRuleVariables returns the ProgramRuleVariables field value if set, zero value otherwise.
func (o *ProgramParams) GetProgramRuleVariables() []ProgramParamsProgramRuleVariablesInner {
	if o == nil || IsNil(o.ProgramRuleVariables) {
		var ret []ProgramParamsProgramRuleVariablesInner
		return ret
	}
	return o.ProgramRuleVariables
}

// GetProgramRuleVariablesOk returns a tuple with the ProgramRuleVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetProgramRuleVariablesOk() ([]ProgramParamsProgramRuleVariablesInner, bool) {
	if o == nil || IsNil(o.ProgramRuleVariables) {
		return nil, false
	}
	return o.ProgramRuleVariables, true
}

// HasProgramRuleVariables returns a boolean if a field has been set.
func (o *ProgramParams) HasProgramRuleVariables() bool {
	if o != nil && !IsNil(o.ProgramRuleVariables) {
		return true
	}

	return false
}

// SetProgramRuleVariables gets a reference to the given []ProgramParamsProgramRuleVariablesInner and assigns it to the ProgramRuleVariables field.
func (o *ProgramParams) SetProgramRuleVariables(v []ProgramParamsProgramRuleVariablesInner) {
	o.ProgramRuleVariables = v
}

// GetProgramSections returns the ProgramSections field value if set, zero value otherwise.
func (o *ProgramParams) GetProgramSections() []ProgramParamsProgramSectionsInner {
	if o == nil || IsNil(o.ProgramSections) {
		var ret []ProgramParamsProgramSectionsInner
		return ret
	}
	return o.ProgramSections
}

// GetProgramSectionsOk returns a tuple with the ProgramSections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetProgramSectionsOk() ([]ProgramParamsProgramSectionsInner, bool) {
	if o == nil || IsNil(o.ProgramSections) {
		return nil, false
	}
	return o.ProgramSections, true
}

// HasProgramSections returns a boolean if a field has been set.
func (o *ProgramParams) HasProgramSections() bool {
	if o != nil && !IsNil(o.ProgramSections) {
		return true
	}

	return false
}

// SetProgramSections gets a reference to the given []ProgramParamsProgramSectionsInner and assigns it to the ProgramSections field.
func (o *ProgramParams) SetProgramSections(v []ProgramParamsProgramSectionsInner) {
	o.ProgramSections = v
}

// GetProgramStageLabel returns the ProgramStageLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetProgramStageLabel() string {
	if o == nil || IsNil(o.ProgramStageLabel) {
		var ret string
		return ret
	}
	return *o.ProgramStageLabel
}

// GetProgramStageLabelOk returns a tuple with the ProgramStageLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetProgramStageLabelOk() (*string, bool) {
	if o == nil || IsNil(o.ProgramStageLabel) {
		return nil, false
	}
	return o.ProgramStageLabel, true
}

// HasProgramStageLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasProgramStageLabel() bool {
	if o != nil && !IsNil(o.ProgramStageLabel) {
		return true
	}

	return false
}

// SetProgramStageLabel gets a reference to the given string and assigns it to the ProgramStageLabel field.
func (o *ProgramParams) SetProgramStageLabel(v string) {
	o.ProgramStageLabel = &v
}

// GetProgramStages returns the ProgramStages field value if set, zero value otherwise.
func (o *ProgramParams) GetProgramStages() []ProgramParamsProgramStagesInner {
	if o == nil || IsNil(o.ProgramStages) {
		var ret []ProgramParamsProgramStagesInner
		return ret
	}
	return o.ProgramStages
}

// GetProgramStagesOk returns a tuple with the ProgramStages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetProgramStagesOk() ([]ProgramParamsProgramStagesInner, bool) {
	if o == nil || IsNil(o.ProgramStages) {
		return nil, false
	}
	return o.ProgramStages, true
}

// HasProgramStages returns a boolean if a field has been set.
func (o *ProgramParams) HasProgramStages() bool {
	if o != nil && !IsNil(o.ProgramStages) {
		return true
	}

	return false
}

// SetProgramStages gets a reference to the given []ProgramParamsProgramStagesInner and assigns it to the ProgramStages field.
func (o *ProgramParams) SetProgramStages(v []ProgramParamsProgramStagesInner) {
	o.ProgramStages = v
}

// GetProgramTrackedEntityAttributes returns the ProgramTrackedEntityAttributes field value if set, zero value otherwise.
func (o *ProgramParams) GetProgramTrackedEntityAttributes() []ProgramTrackedEntityAttributeParams {
	if o == nil || IsNil(o.ProgramTrackedEntityAttributes) {
		var ret []ProgramTrackedEntityAttributeParams
		return ret
	}
	return o.ProgramTrackedEntityAttributes
}

// GetProgramTrackedEntityAttributesOk returns a tuple with the ProgramTrackedEntityAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetProgramTrackedEntityAttributesOk() ([]ProgramTrackedEntityAttributeParams, bool) {
	if o == nil || IsNil(o.ProgramTrackedEntityAttributes) {
		return nil, false
	}
	return o.ProgramTrackedEntityAttributes, true
}

// HasProgramTrackedEntityAttributes returns a boolean if a field has been set.
func (o *ProgramParams) HasProgramTrackedEntityAttributes() bool {
	if o != nil && !IsNil(o.ProgramTrackedEntityAttributes) {
		return true
	}

	return false
}

// SetProgramTrackedEntityAttributes gets a reference to the given []ProgramTrackedEntityAttributeParams and assigns it to the ProgramTrackedEntityAttributes field.
func (o *ProgramParams) SetProgramTrackedEntityAttributes(v []ProgramTrackedEntityAttributeParams) {
	o.ProgramTrackedEntityAttributes = v
}

// GetProgramType returns the ProgramType field value
func (o *ProgramParams) GetProgramType() ProgramType {
	if o == nil {
		var ret ProgramType
		return ret
	}

	return o.ProgramType
}

// GetProgramTypeOk returns a tuple with the ProgramType field value
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetProgramTypeOk() (*ProgramType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProgramType, true
}

// SetProgramType sets field value
func (o *ProgramParams) SetProgramType(v ProgramType) {
	o.ProgramType = v
}

// GetRegistration returns the Registration field value if set, zero value otherwise.
func (o *ProgramParams) GetRegistration() bool {
	if o == nil || IsNil(o.Registration) {
		var ret bool
		return ret
	}
	return *o.Registration
}

// GetRegistrationOk returns a tuple with the Registration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetRegistrationOk() (*bool, bool) {
	if o == nil || IsNil(o.Registration) {
		return nil, false
	}
	return o.Registration, true
}

// HasRegistration returns a boolean if a field has been set.
func (o *ProgramParams) HasRegistration() bool {
	if o != nil && !IsNil(o.Registration) {
		return true
	}

	return false
}

// SetRegistration gets a reference to the given bool and assigns it to the Registration field.
func (o *ProgramParams) SetRegistration(v bool) {
	o.Registration = &v
}

// GetRelatedProgram returns the RelatedProgram field value if set, zero value otherwise.
func (o *ProgramParams) GetRelatedProgram() ProgramParams {
	if o == nil || IsNil(o.RelatedProgram) {
		var ret ProgramParams
		return ret
	}
	return *o.RelatedProgram
}

// GetRelatedProgramOk returns a tuple with the RelatedProgram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetRelatedProgramOk() (*ProgramParams, bool) {
	if o == nil || IsNil(o.RelatedProgram) {
		return nil, false
	}
	return o.RelatedProgram, true
}

// HasRelatedProgram returns a boolean if a field has been set.
func (o *ProgramParams) HasRelatedProgram() bool {
	if o != nil && !IsNil(o.RelatedProgram) {
		return true
	}

	return false
}

// SetRelatedProgram gets a reference to the given ProgramParams and assigns it to the RelatedProgram field.
func (o *ProgramParams) SetRelatedProgram(v ProgramParams) {
	o.RelatedProgram = &v
}

// GetRelationshipLabel returns the RelationshipLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetRelationshipLabel() string {
	if o == nil || IsNil(o.RelationshipLabel) {
		var ret string
		return ret
	}
	return *o.RelationshipLabel
}

// GetRelationshipLabelOk returns a tuple with the RelationshipLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetRelationshipLabelOk() (*string, bool) {
	if o == nil || IsNil(o.RelationshipLabel) {
		return nil, false
	}
	return o.RelationshipLabel, true
}

// HasRelationshipLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasRelationshipLabel() bool {
	if o != nil && !IsNil(o.RelationshipLabel) {
		return true
	}

	return false
}

// SetRelationshipLabel gets a reference to the given string and assigns it to the RelationshipLabel field.
func (o *ProgramParams) SetRelationshipLabel(v string) {
	o.RelationshipLabel = &v
}

// GetSelectEnrollmentDatesInFuture returns the SelectEnrollmentDatesInFuture field value if set, zero value otherwise.
func (o *ProgramParams) GetSelectEnrollmentDatesInFuture() bool {
	if o == nil || IsNil(o.SelectEnrollmentDatesInFuture) {
		var ret bool
		return ret
	}
	return *o.SelectEnrollmentDatesInFuture
}

// GetSelectEnrollmentDatesInFutureOk returns a tuple with the SelectEnrollmentDatesInFuture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetSelectEnrollmentDatesInFutureOk() (*bool, bool) {
	if o == nil || IsNil(o.SelectEnrollmentDatesInFuture) {
		return nil, false
	}
	return o.SelectEnrollmentDatesInFuture, true
}

// HasSelectEnrollmentDatesInFuture returns a boolean if a field has been set.
func (o *ProgramParams) HasSelectEnrollmentDatesInFuture() bool {
	if o != nil && !IsNil(o.SelectEnrollmentDatesInFuture) {
		return true
	}

	return false
}

// SetSelectEnrollmentDatesInFuture gets a reference to the given bool and assigns it to the SelectEnrollmentDatesInFuture field.
func (o *ProgramParams) SetSelectEnrollmentDatesInFuture(v bool) {
	o.SelectEnrollmentDatesInFuture = &v
}

// GetSelectIncidentDatesInFuture returns the SelectIncidentDatesInFuture field value if set, zero value otherwise.
func (o *ProgramParams) GetSelectIncidentDatesInFuture() bool {
	if o == nil || IsNil(o.SelectIncidentDatesInFuture) {
		var ret bool
		return ret
	}
	return *o.SelectIncidentDatesInFuture
}

// GetSelectIncidentDatesInFutureOk returns a tuple with the SelectIncidentDatesInFuture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetSelectIncidentDatesInFutureOk() (*bool, bool) {
	if o == nil || IsNil(o.SelectIncidentDatesInFuture) {
		return nil, false
	}
	return o.SelectIncidentDatesInFuture, true
}

// HasSelectIncidentDatesInFuture returns a boolean if a field has been set.
func (o *ProgramParams) HasSelectIncidentDatesInFuture() bool {
	if o != nil && !IsNil(o.SelectIncidentDatesInFuture) {
		return true
	}

	return false
}

// SetSelectIncidentDatesInFuture gets a reference to the given bool and assigns it to the SelectIncidentDatesInFuture field.
func (o *ProgramParams) SetSelectIncidentDatesInFuture(v bool) {
	o.SelectIncidentDatesInFuture = &v
}

// GetSharing returns the Sharing field value if set, zero value otherwise.
func (o *ProgramParams) GetSharing() Sharing {
	if o == nil || IsNil(o.Sharing) {
		var ret Sharing
		return ret
	}
	return *o.Sharing
}

// GetSharingOk returns a tuple with the Sharing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetSharingOk() (*Sharing, bool) {
	if o == nil || IsNil(o.Sharing) {
		return nil, false
	}
	return o.Sharing, true
}

// HasSharing returns a boolean if a field has been set.
func (o *ProgramParams) HasSharing() bool {
	if o != nil && !IsNil(o.Sharing) {
		return true
	}

	return false
}

// SetSharing gets a reference to the given Sharing and assigns it to the Sharing field.
func (o *ProgramParams) SetSharing(v Sharing) {
	o.Sharing = &v
}

// GetShortName returns the ShortName field value if set, zero value otherwise.
func (o *ProgramParams) GetShortName() string {
	if o == nil || IsNil(o.ShortName) {
		var ret string
		return ret
	}
	return *o.ShortName
}

// GetShortNameOk returns a tuple with the ShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetShortNameOk() (*string, bool) {
	if o == nil || IsNil(o.ShortName) {
		return nil, false
	}
	return o.ShortName, true
}

// HasShortName returns a boolean if a field has been set.
func (o *ProgramParams) HasShortName() bool {
	if o != nil && !IsNil(o.ShortName) {
		return true
	}

	return false
}

// SetShortName gets a reference to the given string and assigns it to the ShortName field.
func (o *ProgramParams) SetShortName(v string) {
	o.ShortName = &v
}

// GetSkipOffline returns the SkipOffline field value if set, zero value otherwise.
func (o *ProgramParams) GetSkipOffline() bool {
	if o == nil || IsNil(o.SkipOffline) {
		var ret bool
		return ret
	}
	return *o.SkipOffline
}

// GetSkipOfflineOk returns a tuple with the SkipOffline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetSkipOfflineOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipOffline) {
		return nil, false
	}
	return o.SkipOffline, true
}

// HasSkipOffline returns a boolean if a field has been set.
func (o *ProgramParams) HasSkipOffline() bool {
	if o != nil && !IsNil(o.SkipOffline) {
		return true
	}

	return false
}

// SetSkipOffline gets a reference to the given bool and assigns it to the SkipOffline field.
func (o *ProgramParams) SetSkipOffline(v bool) {
	o.SkipOffline = &v
}

// GetStyle returns the Style field value if set, zero value otherwise.
func (o *ProgramParams) GetStyle() ObjectStyle {
	if o == nil || IsNil(o.Style) {
		var ret ObjectStyle
		return ret
	}
	return *o.Style
}

// GetStyleOk returns a tuple with the Style field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetStyleOk() (*ObjectStyle, bool) {
	if o == nil || IsNil(o.Style) {
		return nil, false
	}
	return o.Style, true
}

// HasStyle returns a boolean if a field has been set.
func (o *ProgramParams) HasStyle() bool {
	if o != nil && !IsNil(o.Style) {
		return true
	}

	return false
}

// SetStyle gets a reference to the given ObjectStyle and assigns it to the Style field.
func (o *ProgramParams) SetStyle(v ObjectStyle) {
	o.Style = &v
}

// GetTrackedEntityAttributeLabel returns the TrackedEntityAttributeLabel field value if set, zero value otherwise.
func (o *ProgramParams) GetTrackedEntityAttributeLabel() string {
	if o == nil || IsNil(o.TrackedEntityAttributeLabel) {
		var ret string
		return ret
	}
	return *o.TrackedEntityAttributeLabel
}

// GetTrackedEntityAttributeLabelOk returns a tuple with the TrackedEntityAttributeLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetTrackedEntityAttributeLabelOk() (*string, bool) {
	if o == nil || IsNil(o.TrackedEntityAttributeLabel) {
		return nil, false
	}
	return o.TrackedEntityAttributeLabel, true
}

// HasTrackedEntityAttributeLabel returns a boolean if a field has been set.
func (o *ProgramParams) HasTrackedEntityAttributeLabel() bool {
	if o != nil && !IsNil(o.TrackedEntityAttributeLabel) {
		return true
	}

	return false
}

// SetTrackedEntityAttributeLabel gets a reference to the given string and assigns it to the TrackedEntityAttributeLabel field.
func (o *ProgramParams) SetTrackedEntityAttributeLabel(v string) {
	o.TrackedEntityAttributeLabel = &v
}

// GetTrackedEntityType returns the TrackedEntityType field value if set, zero value otherwise.
func (o *ProgramParams) GetTrackedEntityType() MapViewParamsTrackedEntityType {
	if o == nil || IsNil(o.TrackedEntityType) {
		var ret MapViewParamsTrackedEntityType
		return ret
	}
	return *o.TrackedEntityType
}

// GetTrackedEntityTypeOk returns a tuple with the TrackedEntityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetTrackedEntityTypeOk() (*MapViewParamsTrackedEntityType, bool) {
	if o == nil || IsNil(o.TrackedEntityType) {
		return nil, false
	}
	return o.TrackedEntityType, true
}

// HasTrackedEntityType returns a boolean if a field has been set.
func (o *ProgramParams) HasTrackedEntityType() bool {
	if o != nil && !IsNil(o.TrackedEntityType) {
		return true
	}

	return false
}

// SetTrackedEntityType gets a reference to the given MapViewParamsTrackedEntityType and assigns it to the TrackedEntityType field.
func (o *ProgramParams) SetTrackedEntityType(v MapViewParamsTrackedEntityType) {
	o.TrackedEntityType = &v
}

// GetTranslations returns the Translations field value if set, zero value otherwise.
func (o *ProgramParams) GetTranslations() []Translation {
	if o == nil || IsNil(o.Translations) {
		var ret []Translation
		return ret
	}
	return o.Translations
}

// GetTranslationsOk returns a tuple with the Translations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetTranslationsOk() ([]Translation, bool) {
	if o == nil || IsNil(o.Translations) {
		return nil, false
	}
	return o.Translations, true
}

// HasTranslations returns a boolean if a field has been set.
func (o *ProgramParams) HasTranslations() bool {
	if o != nil && !IsNil(o.Translations) {
		return true
	}

	return false
}

// SetTranslations gets a reference to the given []Translation and assigns it to the Translations field.
func (o *ProgramParams) SetTranslations(v []Translation) {
	o.Translations = v
}

// GetUseFirstStageDuringRegistration returns the UseFirstStageDuringRegistration field value if set, zero value otherwise.
func (o *ProgramParams) GetUseFirstStageDuringRegistration() bool {
	if o == nil || IsNil(o.UseFirstStageDuringRegistration) {
		var ret bool
		return ret
	}
	return *o.UseFirstStageDuringRegistration
}

// GetUseFirstStageDuringRegistrationOk returns a tuple with the UseFirstStageDuringRegistration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetUseFirstStageDuringRegistrationOk() (*bool, bool) {
	if o == nil || IsNil(o.UseFirstStageDuringRegistration) {
		return nil, false
	}
	return o.UseFirstStageDuringRegistration, true
}

// HasUseFirstStageDuringRegistration returns a boolean if a field has been set.
func (o *ProgramParams) HasUseFirstStageDuringRegistration() bool {
	if o != nil && !IsNil(o.UseFirstStageDuringRegistration) {
		return true
	}

	return false
}

// SetUseFirstStageDuringRegistration gets a reference to the given bool and assigns it to the UseFirstStageDuringRegistration field.
func (o *ProgramParams) SetUseFirstStageDuringRegistration(v bool) {
	o.UseFirstStageDuringRegistration = &v
}

// GetUserRoles returns the UserRoles field value if set, zero value otherwise.
func (o *ProgramParams) GetUserRoles() []ProgramParamsUserRolesInner {
	if o == nil || IsNil(o.UserRoles) {
		var ret []ProgramParamsUserRolesInner
		return ret
	}
	return o.UserRoles
}

// GetUserRolesOk returns a tuple with the UserRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetUserRolesOk() ([]ProgramParamsUserRolesInner, bool) {
	if o == nil || IsNil(o.UserRoles) {
		return nil, false
	}
	return o.UserRoles, true
}

// HasUserRoles returns a boolean if a field has been set.
func (o *ProgramParams) HasUserRoles() bool {
	if o != nil && !IsNil(o.UserRoles) {
		return true
	}

	return false
}

// SetUserRoles gets a reference to the given []ProgramParamsUserRolesInner and assigns it to the UserRoles field.
func (o *ProgramParams) SetUserRoles(v []ProgramParamsUserRolesInner) {
	o.UserRoles = v
}

// GetVersion returns the Version field value
func (o *ProgramParams) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ProgramParams) SetVersion(v int32) {
	o.Version = v
}

// GetWithoutRegistration returns the WithoutRegistration field value if set, zero value otherwise.
func (o *ProgramParams) GetWithoutRegistration() bool {
	if o == nil || IsNil(o.WithoutRegistration) {
		var ret bool
		return ret
	}
	return *o.WithoutRegistration
}

// GetWithoutRegistrationOk returns a tuple with the WithoutRegistration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramParams) GetWithoutRegistrationOk() (*bool, bool) {
	if o == nil || IsNil(o.WithoutRegistration) {
		return nil, false
	}
	return o.WithoutRegistration, true
}

// HasWithoutRegistration returns a boolean if a field has been set.
func (o *ProgramParams) HasWithoutRegistration() bool {
	if o != nil && !IsNil(o.WithoutRegistration) {
		return true
	}

	return false
}

// SetWithoutRegistration gets a reference to the given bool and assigns it to the WithoutRegistration field.
func (o *ProgramParams) SetWithoutRegistration(v bool) {
	o.WithoutRegistration = &v
}

func (o ProgramParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProgramParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accessLevel"] = o.AccessLevel
	if !IsNil(o.AttributeValues) {
		toSerialize["attributeValues"] = o.AttributeValues
	}
	if !IsNil(o.CategoryCombo) {
		toSerialize["categoryCombo"] = o.CategoryCombo
	}
	if !IsNil(o.CategoryMappings) {
		toSerialize["categoryMappings"] = o.CategoryMappings
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	toSerialize["completeEventsExpiryDays"] = o.CompleteEventsExpiryDays
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if !IsNil(o.DataEntryForm) {
		toSerialize["dataEntryForm"] = o.DataEntryForm
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DisplayDescription) {
		toSerialize["displayDescription"] = o.DisplayDescription
	}
	if !IsNil(o.DisplayEnrollmentDateLabel) {
		toSerialize["displayEnrollmentDateLabel"] = o.DisplayEnrollmentDateLabel
	}
	if !IsNil(o.DisplayEnrollmentLabel) {
		toSerialize["displayEnrollmentLabel"] = o.DisplayEnrollmentLabel
	}
	if !IsNil(o.DisplayEventLabel) {
		toSerialize["displayEventLabel"] = o.DisplayEventLabel
	}
	if !IsNil(o.DisplayFollowUpLabel) {
		toSerialize["displayFollowUpLabel"] = o.DisplayFollowUpLabel
	}
	if !IsNil(o.DisplayFormName) {
		toSerialize["displayFormName"] = o.DisplayFormName
	}
	if !IsNil(o.DisplayFrontPageList) {
		toSerialize["displayFrontPageList"] = o.DisplayFrontPageList
	}
	if !IsNil(o.DisplayIncidentDate) {
		toSerialize["displayIncidentDate"] = o.DisplayIncidentDate
	}
	if !IsNil(o.DisplayIncidentDateLabel) {
		toSerialize["displayIncidentDateLabel"] = o.DisplayIncidentDateLabel
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.DisplayNoteLabel) {
		toSerialize["displayNoteLabel"] = o.DisplayNoteLabel
	}
	if !IsNil(o.DisplayOrgUnitLabel) {
		toSerialize["displayOrgUnitLabel"] = o.DisplayOrgUnitLabel
	}
	if !IsNil(o.DisplayProgramStageLabel) {
		toSerialize["displayProgramStageLabel"] = o.DisplayProgramStageLabel
	}
	if !IsNil(o.DisplayRelationshipLabel) {
		toSerialize["displayRelationshipLabel"] = o.DisplayRelationshipLabel
	}
	if !IsNil(o.DisplayShortName) {
		toSerialize["displayShortName"] = o.DisplayShortName
	}
	if !IsNil(o.DisplayTrackedEntityAttributeLabel) {
		toSerialize["displayTrackedEntityAttributeLabel"] = o.DisplayTrackedEntityAttributeLabel
	}
	if !IsNil(o.EnrollmentDateLabel) {
		toSerialize["enrollmentDateLabel"] = o.EnrollmentDateLabel
	}
	if !IsNil(o.EnrollmentLabel) {
		toSerialize["enrollmentLabel"] = o.EnrollmentLabel
	}
	if !IsNil(o.EventLabel) {
		toSerialize["eventLabel"] = o.EventLabel
	}
	toSerialize["expiryDays"] = o.ExpiryDays
	if !IsNil(o.ExpiryPeriodType) {
		toSerialize["expiryPeriodType"] = o.ExpiryPeriodType
	}
	if !IsNil(o.Favorite) {
		toSerialize["favorite"] = o.Favorite
	}
	if !IsNil(o.Favorites) {
		toSerialize["favorites"] = o.Favorites
	}
	toSerialize["featureType"] = o.FeatureType
	if !IsNil(o.FollowUpLabel) {
		toSerialize["followUpLabel"] = o.FollowUpLabel
	}
	if !IsNil(o.FormName) {
		toSerialize["formName"] = o.FormName
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IgnoreOverdueEvents) {
		toSerialize["ignoreOverdueEvents"] = o.IgnoreOverdueEvents
	}
	if !IsNil(o.IncidentDateLabel) {
		toSerialize["incidentDateLabel"] = o.IncidentDateLabel
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.LastUpdatedBy) {
		toSerialize["lastUpdatedBy"] = o.LastUpdatedBy
	}
	toSerialize["maxTeiCountToReturn"] = o.MaxTeiCountToReturn
	toSerialize["minAttributesRequiredToSearch"] = o.MinAttributesRequiredToSearch
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NoteLabel) {
		toSerialize["noteLabel"] = o.NoteLabel
	}
	if !IsNil(o.NotificationTemplates) {
		toSerialize["notificationTemplates"] = o.NotificationTemplates
	}
	if !IsNil(o.OnlyEnrollOnce) {
		toSerialize["onlyEnrollOnce"] = o.OnlyEnrollOnce
	}
	toSerialize["openDaysAfterCoEndDate"] = o.OpenDaysAfterCoEndDate
	if !IsNil(o.OrgUnitLabel) {
		toSerialize["orgUnitLabel"] = o.OrgUnitLabel
	}
	if !IsNil(o.OrganisationUnits) {
		toSerialize["organisationUnits"] = o.OrganisationUnits
	}
	if !IsNil(o.ProgramIndicators) {
		toSerialize["programIndicators"] = o.ProgramIndicators
	}
	if !IsNil(o.ProgramRuleVariables) {
		toSerialize["programRuleVariables"] = o.ProgramRuleVariables
	}
	if !IsNil(o.ProgramSections) {
		toSerialize["programSections"] = o.ProgramSections
	}
	if !IsNil(o.ProgramStageLabel) {
		toSerialize["programStageLabel"] = o.ProgramStageLabel
	}
	if !IsNil(o.ProgramStages) {
		toSerialize["programStages"] = o.ProgramStages
	}
	if !IsNil(o.ProgramTrackedEntityAttributes) {
		toSerialize["programTrackedEntityAttributes"] = o.ProgramTrackedEntityAttributes
	}
	toSerialize["programType"] = o.ProgramType
	if !IsNil(o.Registration) {
		toSerialize["registration"] = o.Registration
	}
	if !IsNil(o.RelatedProgram) {
		toSerialize["relatedProgram"] = o.RelatedProgram
	}
	if !IsNil(o.RelationshipLabel) {
		toSerialize["relationshipLabel"] = o.RelationshipLabel
	}
	if !IsNil(o.SelectEnrollmentDatesInFuture) {
		toSerialize["selectEnrollmentDatesInFuture"] = o.SelectEnrollmentDatesInFuture
	}
	if !IsNil(o.SelectIncidentDatesInFuture) {
		toSerialize["selectIncidentDatesInFuture"] = o.SelectIncidentDatesInFuture
	}
	if !IsNil(o.Sharing) {
		toSerialize["sharing"] = o.Sharing
	}
	if !IsNil(o.ShortName) {
		toSerialize["shortName"] = o.ShortName
	}
	if !IsNil(o.SkipOffline) {
		toSerialize["skipOffline"] = o.SkipOffline
	}
	if !IsNil(o.Style) {
		toSerialize["style"] = o.Style
	}
	if !IsNil(o.TrackedEntityAttributeLabel) {
		toSerialize["trackedEntityAttributeLabel"] = o.TrackedEntityAttributeLabel
	}
	if !IsNil(o.TrackedEntityType) {
		toSerialize["trackedEntityType"] = o.TrackedEntityType
	}
	if !IsNil(o.Translations) {
		toSerialize["translations"] = o.Translations
	}
	if !IsNil(o.UseFirstStageDuringRegistration) {
		toSerialize["useFirstStageDuringRegistration"] = o.UseFirstStageDuringRegistration
	}
	if !IsNil(o.UserRoles) {
		toSerialize["userRoles"] = o.UserRoles
	}
	toSerialize["version"] = o.Version
	if !IsNil(o.WithoutRegistration) {
		toSerialize["withoutRegistration"] = o.WithoutRegistration
	}
	return toSerialize, nil
}

func (o *ProgramParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accessLevel",
		"completeEventsExpiryDays",
		"expiryDays",
		"featureType",
		"maxTeiCountToReturn",
		"minAttributesRequiredToSearch",
		"openDaysAfterCoEndDate",
		"programType",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProgramParams := _ProgramParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProgramParams)

	if err != nil {
		return err
	}

	*o = ProgramParams(varProgramParams)

	return err
}

type NullableProgramParams struct {
	value *ProgramParams
	isSet bool
}

func (v NullableProgramParams) Get() *ProgramParams {
	return v.value
}

func (v *NullableProgramParams) Set(val *ProgramParams) {
	v.value = val
	v.isSet = true
}

func (v NullableProgramParams) IsSet() bool {
	return v.isSet
}

func (v *NullableProgramParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgramParams(val *ProgramParams) *NullableProgramParams {
	return &NullableProgramParams{value: val, isSet: true}
}

func (v NullableProgramParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgramParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
