/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the RelationshipItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RelationshipItem{}

// RelationshipItem struct for RelationshipItem
type RelationshipItem struct {
	Enrollment    *BaseIdentifiableObject `json:"enrollment,omitempty"`
	Event         *BaseIdentifiableObject `json:"event,omitempty"`
	Relationship  *BaseIdentifiableObject `json:"relationship,omitempty"`
	TrackedEntity *BaseIdentifiableObject `json:"trackedEntity,omitempty"`
}

// NewRelationshipItem instantiates a new RelationshipItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationshipItem() *RelationshipItem {
	this := RelationshipItem{}
	return &this
}

// NewRelationshipItemWithDefaults instantiates a new RelationshipItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipItemWithDefaults() *RelationshipItem {
	this := RelationshipItem{}
	return &this
}

// GetEnrollment returns the Enrollment field value if set, zero value otherwise.
func (o *RelationshipItem) GetEnrollment() BaseIdentifiableObject {
	if o == nil || IsNil(o.Enrollment) {
		var ret BaseIdentifiableObject
		return ret
	}
	return *o.Enrollment
}

// GetEnrollmentOk returns a tuple with the Enrollment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipItem) GetEnrollmentOk() (*BaseIdentifiableObject, bool) {
	if o == nil || IsNil(o.Enrollment) {
		return nil, false
	}
	return o.Enrollment, true
}

// HasEnrollment returns a boolean if a field has been set.
func (o *RelationshipItem) HasEnrollment() bool {
	if o != nil && !IsNil(o.Enrollment) {
		return true
	}

	return false
}

// SetEnrollment gets a reference to the given BaseIdentifiableObject and assigns it to the Enrollment field.
func (o *RelationshipItem) SetEnrollment(v BaseIdentifiableObject) {
	o.Enrollment = &v
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *RelationshipItem) GetEvent() BaseIdentifiableObject {
	if o == nil || IsNil(o.Event) {
		var ret BaseIdentifiableObject
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipItem) GetEventOk() (*BaseIdentifiableObject, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *RelationshipItem) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given BaseIdentifiableObject and assigns it to the Event field.
func (o *RelationshipItem) SetEvent(v BaseIdentifiableObject) {
	o.Event = &v
}

// GetRelationship returns the Relationship field value if set, zero value otherwise.
func (o *RelationshipItem) GetRelationship() BaseIdentifiableObject {
	if o == nil || IsNil(o.Relationship) {
		var ret BaseIdentifiableObject
		return ret
	}
	return *o.Relationship
}

// GetRelationshipOk returns a tuple with the Relationship field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipItem) GetRelationshipOk() (*BaseIdentifiableObject, bool) {
	if o == nil || IsNil(o.Relationship) {
		return nil, false
	}
	return o.Relationship, true
}

// HasRelationship returns a boolean if a field has been set.
func (o *RelationshipItem) HasRelationship() bool {
	if o != nil && !IsNil(o.Relationship) {
		return true
	}

	return false
}

// SetRelationship gets a reference to the given BaseIdentifiableObject and assigns it to the Relationship field.
func (o *RelationshipItem) SetRelationship(v BaseIdentifiableObject) {
	o.Relationship = &v
}

// GetTrackedEntity returns the TrackedEntity field value if set, zero value otherwise.
func (o *RelationshipItem) GetTrackedEntity() BaseIdentifiableObject {
	if o == nil || IsNil(o.TrackedEntity) {
		var ret BaseIdentifiableObject
		return ret
	}
	return *o.TrackedEntity
}

// GetTrackedEntityOk returns a tuple with the TrackedEntity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipItem) GetTrackedEntityOk() (*BaseIdentifiableObject, bool) {
	if o == nil || IsNil(o.TrackedEntity) {
		return nil, false
	}
	return o.TrackedEntity, true
}

// HasTrackedEntity returns a boolean if a field has been set.
func (o *RelationshipItem) HasTrackedEntity() bool {
	if o != nil && !IsNil(o.TrackedEntity) {
		return true
	}

	return false
}

// SetTrackedEntity gets a reference to the given BaseIdentifiableObject and assigns it to the TrackedEntity field.
func (o *RelationshipItem) SetTrackedEntity(v BaseIdentifiableObject) {
	o.TrackedEntity = &v
}

func (o RelationshipItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RelationshipItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enrollment) {
		toSerialize["enrollment"] = o.Enrollment
	}
	if !IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !IsNil(o.Relationship) {
		toSerialize["relationship"] = o.Relationship
	}
	if !IsNil(o.TrackedEntity) {
		toSerialize["trackedEntity"] = o.TrackedEntity
	}
	return toSerialize, nil
}

type NullableRelationshipItem struct {
	value *RelationshipItem
	isSet bool
}

func (v NullableRelationshipItem) Get() *RelationshipItem {
	return v.value
}

func (v *NullableRelationshipItem) Set(val *RelationshipItem) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationshipItem) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationshipItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationshipItem(val *RelationshipItem) *NullableRelationshipItem {
	return &NullableRelationshipItem{value: val, isSet: true}
}

func (v NullableRelationshipItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationshipItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
