/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.40
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response - struct for TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response
type TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response struct {
	TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf *TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	ArrayOfMapmapOfStringAny                                                           *[]map[string]interface{}
}

// TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfAsTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response is a convenience function that returns TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf wrapped in TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response
func TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfAsTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response(v *TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response {
	return TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response{
		TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf: v,
	}
}

// []map[string]interface{}AsTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response is a convenience function that returns []map[string]interface{} wrapped in TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response
func ArrayOfMapmapOfStringAnyAsTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response(v *[]map[string]interface{}) TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response {
	return TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response{
		ArrayOfMapmapOfStringAny: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf)
	if err == nil {
		jsonTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf, _ := json.Marshal(dst.TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf)
		if string(jsonTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) == "{}" { // empty struct
			dst.TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf = nil
		} else {
			match++
		}
	} else {
		dst.TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf = nil
	}

	// try to unmarshal data into ArrayOfMapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.ArrayOfMapmapOfStringAny)
	if err == nil {
		jsonArrayOfMapmapOfStringAny, _ := json.Marshal(dst.ArrayOfMapmapOfStringAny)
		if string(jsonArrayOfMapmapOfStringAny) == "{}" { // empty struct
			dst.ArrayOfMapmapOfStringAny = nil
		} else {
			match++
		}
	} else {
		dst.ArrayOfMapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf = nil
		dst.ArrayOfMapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) MarshalJSON() ([]byte, error) {
	if src.TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf != nil {
		return json.Marshal(&src.TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf)
	}

	if src.ArrayOfMapmapOfStringAny != nil {
		return json.Marshal(&src.ArrayOfMapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf != nil {
		return obj.TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	}

	if obj.ArrayOfMapmapOfStringAny != nil {
		return obj.ArrayOfMapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response struct {
	value *TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response
	isSet bool
}

func (v NullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) Get() *TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response {
	return v.value
}

func (v *NullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) Set(val *TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response(val *TrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) *NullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response {
	return &NullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response{value: val, isSet: true}
}

func (v NullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackedEntityInstanceFilterGetObjectListGistGetObjectListGistAsCsv200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
