/*
DHIS2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.42
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schema

import (
	"encoding/json"
	"fmt"
)

// ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response - struct for ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response
type ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response struct {
	ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf *ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	ArrayOfValidationRuleGroup                                                 *[]ValidationRuleGroup
}

// ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfAsValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response is a convenience function that returns ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf wrapped in ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response
func ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOfAsValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response(v *ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response {
	return ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response{
		ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf: v,
	}
}

// []ValidationRuleGroupAsValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response is a convenience function that returns []ValidationRuleGroup wrapped in ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response
func ArrayOfValidationRuleGroupAsValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response(v *[]ValidationRuleGroup) ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response {
	return ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response{
		ArrayOfValidationRuleGroup: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf)
	if err == nil {
		jsonValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf, _ := json.Marshal(dst.ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf)
		if string(jsonValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf) == "{}" { // empty struct
			dst.ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf = nil
		} else {
			match++
		}
	} else {
		dst.ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf = nil
	}

	// try to unmarshal data into ArrayOfValidationRuleGroup
	err = newStrictDecoder(data).Decode(&dst.ArrayOfValidationRuleGroup)
	if err == nil {
		jsonArrayOfValidationRuleGroup, _ := json.Marshal(dst.ArrayOfValidationRuleGroup)
		if string(jsonArrayOfValidationRuleGroup) == "{}" { // empty struct
			dst.ArrayOfValidationRuleGroup = nil
		} else {
			match++
		}
	} else {
		dst.ArrayOfValidationRuleGroup = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf = nil
		dst.ArrayOfValidationRuleGroup = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) MarshalJSON() ([]byte, error) {
	if src.ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf != nil {
		return json.Marshal(&src.ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf)
	}

	if src.ArrayOfValidationRuleGroup != nil {
		return json.Marshal(&src.ArrayOfValidationRuleGroup)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf != nil {
		return obj.ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200ResponseOneOf
	}

	if obj.ArrayOfValidationRuleGroup != nil {
		return obj.ArrayOfValidationRuleGroup
	}

	// all schemas are nil
	return nil
}

type NullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response struct {
	value *ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response
	isSet bool
}

func (v NullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) Get() *ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response {
	return v.value
}

func (v *NullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) Set(val *ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response(val *ValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) *NullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response {
	return &NullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response{value: val, isSet: true}
}

func (v NullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationRuleGroupGetObjectListGistGetObjectListGistAsCsv200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
